"""Standalone local graph explorer, all evidence inline; no external JS or services."""
import base64, gzip, json
from pathlib import Path
D=Path(__file__).resolve().parent
def read(p):return json.loads(p.read_text())

def build_viewer():
    summary=read(D/'summary.json'); summary=json.loads(json.dumps(summary));
    for domain in ['iTE','TG']:
        g=read(D/domain/'graph.json'); st=summary['domain_stats'][domain]; st.update(concept_nodes=len(g['nodes']),claims=len(g['edges']),original_local_nodes=sum(len(n.get('active_mention_ids',[])) for n in g['nodes']),normalization_uncertain_nodes=sum('uncertain' in n.get('normalization_status','') for n in g['nodes']),core_scope_claims=sum(e['scope'] in {'intrinsic_material_mechanism','thermodynamics','ion_mass_transport','electrode_interface_kinetics'} for e in g['edges']))
    data={'summary':summary,'domains':{},'quotes':[]}; quotes={}
    def qid(q):
        if q not in quotes: quotes[q]=len(data['quotes']);data['quotes'].append(q)
        return quotes[q]
    for domain in ['iTE','TG']:
        graph=read(D/domain/'graph.json'); ns=graph['nodes']; index={n['concept_id']:i for i,n in enumerate(ns)}
        data['domains'][domain]={
            'nodes':[{k:n[k] for k in ['concept_id','label','definition','aliases','roles','normalization_status','normalization_reason','claim_count','source_document_count','paper_ids']} for n in ns],
            'edges':[dict(id=e['claim_id'],s=index[e['source']],t=index[e['target']],p=e['predicate'],paper=e['paper_id'],title=e['paper_title'],doi=e['doi'],year=e['year'],subject=e['subject'],object=e['object'],conditions=e['conditions'],joint=e['joint_factors'],assertion=e['assertion'],modality=e['modality'],scope=e['scope'],review=e['review_status'],claim_scope=e['claim_scope'],article_role=e['article_role'],q=[qid(q) for q in [e['quote']]+e['context_quotes']]) for e in graph['edges']]
        }
    payload=base64.b64encode(gzip.compress(json.dumps(data,ensure_ascii=False,separators=(',',':')).encode())).decode()
    html=TEMPLATE.replace('__PAYLOAD__',payload)
    (D/'index.html').write_text(html)
    print('viewer_bytes',len(html.encode()))

TEMPLATE=r'''<!doctype html>
<html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>iTE / TG · 完整摘要修订版图谱</title>
<style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#23333b;background:#f5f7f7}*{box-sizing:border-box}body{margin:0}header{padding:28px 4vw 18px;background:#113b43;color:white}h1{font-size:25px;margin:0 0 8px;font-weight:650}p{line-height:1.6}header p{margin:0;color:#d3e4e5;font-size:14px}.wrap{max-width:1500px;margin:auto;padding:22px 3vw}.notice{border-left:4px solid #ca9b4d;background:#fff7e9;padding:12px 16px;font-size:13px;line-height:1.7;margin-bottom:18px}.metrics{display:flex;gap:14px;flex-wrap:wrap;margin-bottom:18px}.metric{background:white;padding:15px 20px;border:1px solid #e0e6e6;border-radius:9px;flex:1;min-width:170px}.metric b{font-size:25px;display:block;color:#115c67}.metric span{font-size:13px;color:#5a6b70}.controls{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:16px}input,select,button{font:inherit;border:1px solid #c7d3d5;border-radius:6px;padding:9px;background:white}input{min-width:260px;flex:1}button{cursor:pointer;color:#115c67}button:hover{background:#e7f1f1}.grid{display:grid;grid-template-columns:280px 1fr;gap:18px}.panel{background:white;border:1px solid #e0e6e6;border-radius:10px;padding:18px;overflow:hidden}h2{font-size:17px;margin:0 0 12px}#results{max-height:585px;overflow:auto}#results button{display:block;text-align:left;width:100%;border:0;border-bottom:1px solid #edf0f0;border-radius:0;font-size:13px}small,.muted{color:#63767c;font-size:12px}#diagram{width:100%;height:490px;background:#fbfdfd;border:1px solid #eef2f2;border-radius:7px}.node{cursor:pointer}.node:hover circle{stroke:#da9b37;stroke-width:3}.node text{font-size:16px;fill:#243f47}.node circle{fill:#d6e9e9;stroke:#8fb9bd}.node.selected circle{fill:#165b68;stroke:#165b68}.node.selected text{font-weight:bold}.edge{stroke:#b4c5c7;fill:none}.detail{font-size:13px;line-height:1.6}.tag{display:inline-block;background:#edf4f4;padding:2px 7px;border-radius:4px;margin:2px;font-size:12px}details{border-top:1px solid #e5ebeb;padding:12px 0}summary{cursor:pointer;font-size:14px;line-height:1.6}blockquote{margin:10px 0;padding:10px 14px;background:#f4f7f8;border-left:3px solid #80adb5;font-size:13px;white-space:pre-wrap;line-height:1.6}.files{display:flex;gap:15px;flex-wrap:wrap;margin-top:16px;font-size:13px}a{color:#126571}footer{padding:20px 0;font-size:12px;color:#61787b}.error{color:#a32626}#edgeHeading{margin-top:24px}.loading{padding:35px}.scopeStats{font-size:12px;margin:14px 0;line-height:1.7}@media(max-width:850px){.grid{grid-template-columns:1fr}#results{max-height:200px}#diagram{height:430px}}
</style>
<header><h1>iTE / TG · 完整摘要修订版图谱</h1><p>域内概念整理 · 原始主张逐条保留 · 选择节点查看关系与原文</p></header>
<main class="wrap"><div class="notice">2026-09-25 完整摘要修订版 · 1,971 篇，24,311 条接受关系；426 条待定关系单列。预留模型验收：iTE / TG 严格精确率 82.94% / 89.96%，核心完整覆盖 86.76% / 86.54%。本版未全面达到质量目标；14 条拒绝记录中另有 5 条被判误删。箭头表示原文关系方向，不等于因果或跨域可迁移证明。</div>
<div id="loading" class="loading">正在读取本地数据…</div><div id="app" hidden>
<div class="metrics" id="metrics"></div>
<div class="controls"><label>领域 <select id="domain"><option>iTE</option><option>TG</option></select></label><input id="search" placeholder="搜索规范名称或原始别名…" aria-label="搜索概念"><label>关系范围 <select id="scope"><option value="all">全部保留范围</option><option value="core">核心机制范围</option></select></label><button id="top">按文献支持数浏览</button></div>
<div class="grid"><aside class="panel"><h2>概念列表</h2><small id="resultCount"></small><div id="results"></div><div class="scopeStats" id="scopeStats"></div></aside>
<section class="panel"><h2 id="nodeTitle"></h2><div id="nodeMeta" class="detail"></div><svg id="diagram" viewBox="0 0 900 490" role="img" aria-label="所选节点的一跳邻域"></svg><small id="diagramNote"></small><h2 id="edgeHeading">原始关系与证据</h2><div id="edges"></div><button id="more" hidden>显示更多关系</button></section></div>
<div class="files"><a id="jsonLink" download>当前领域 JSON</a><a id="graphmlLink" download>当前领域 GraphML</a><a id="nodesLink" download>当前领域节点 CSV</a><a id="relationsLink" download>当前领域关系 CSV</a><a href="node_mapping.json" download>原始节点映射</a><a href="deferred_relations.json" download>待定关系</a><a href="mapping_uncertain.json" download>归一化待定</a><a href="../acceptance/REPORT.md">完成报告</a></div>
<footer>每条边对应一条来源主张；规范概念的定义是模型归一化注释。文献支持数按 DOI 去重，不能解释为独立实验验证次数。局部预览最多显示 12 个邻居，完整节点与关系以下载文件为准。</footer></div></main>
<script id="payload" type="application/octet-stream">__PAYLOAD__</script>
<script>
let DATA,G,domain='iTE',selected=0,adj=[],shown=40,activeEdges=[];
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const core=new Set(['intrinsic_material_mechanism','thermodynamics','ion_mass_transport','electrode_interface_kinetics']);
const statuses={model_merged:'模型确认合并',model_kept_separate:'模型确认分开',model_uncertain_retained:'模型待定，保留独立',singleton_not_semantically_reviewed:'单例保留，未做语义判断',new_endpoint_model_separate:'新端点：独立保留',new_endpoint_model_uncertain:'新端点：映射待定',new_singleton_no_exact_alias_candidate:'新端点：暂无确切别名候选'};
function edgeAllowed(e){return $('scope').value==='all'||core.has(e.scope)}
function setDomain(){domain=$('domain').value;G=DATA.domains[domain];adj=G.nodes.map(()=>[]);G.edges.forEach((e,i)=>{adj[e.s].push(i);if(e.t!==e.s)adj[e.t].push(i)});const st=DATA.summary.domain_stats[domain];$('metrics').innerHTML=[[st.concept_nodes,'规范概念 / 保留独立节点'],[st.claims,'原始主张边'],[st.original_local_nodes-st.concept_nodes,'减少的重复节点'],[st.normalization_uncertain_nodes,'归一化待定节点']].map(([n,l])=>'<div class="metric"><b>'+n.toLocaleString()+'</b><span>'+l+'</span></div>').join('');$('scopeStats').textContent='核心机制主张 '+st.core_scope_claims.toLocaleString()+' 条；待定关系 '+st.deferred_claims+' 条未进入主图。';for(const [id,f]of [['jsonLink','graph.json'],['graphmlLink','graph.graphml'],['nodesLink','nodes.csv'],['relationsLink','relations.csv']])$(id).href=domain+'/'+f;search();selectNode(sortedNodes()[0]);}
function sortedNodes(){return G.nodes.map((_,i)=>i).sort((a,b)=>G.nodes[b].source_document_count-G.nodes[a].source_document_count||a-b)}
function search(){const term=$('search').value.toLowerCase().trim();const ids=sortedNodes().filter(i=>!term||[G.nodes[i].label,...G.nodes[i].aliases].some(x=>x.toLowerCase().includes(term)));$('resultCount').textContent=ids.length+' 个结果，显示前 100 个';$('results').innerHTML=ids.slice(0,100).map(i=>'<button data-node="'+i+'">'+esc(G.nodes[i].label)+'<br><small>'+G.nodes[i].source_document_count+' 篇文献 · '+G.nodes[i].claim_count+' 条主张</small></button>').join('');$('results').querySelectorAll('button').forEach(b=>b.onclick=()=>selectNode(Number(b.dataset.node)));}
function selectNode(i){selected=i;shown=40;const n=G.nodes[i];$('nodeTitle').textContent=n.label;$('nodeMeta').innerHTML='<span class="tag">'+esc(statuses[n.normalization_status]||n.normalization_status)+'</span><span class="tag">'+esc(n.roles.join(' / '))+'</span><p>'+esc(n.definition||'未额外生成概念定义，保留原始名称。')+'</p><small>规范编号：'+esc(n.concept_id)+'<br>原始表达：'+esc(n.aliases.join('；'))+'<br>归一化依据：'+esc(n.normalization_reason)+'</small>';activeEdges=adj[i].filter(j=>edgeAllowed(G.edges[j]));draw();renderEdges();}
function draw(){const counts=new Map();for(const j of activeEdges){const e=G.edges[j],other=e.s===selected?e.t:e.s;counts.set(other,(counts.get(other)||0)+1)}const neighbors=[...counts].filter(([i])=>i!==selected).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([i])=>i);const pos=new Map([[selected,[450,240]]]);neighbors.forEach((i,k)=>{const a=2*Math.PI*k/Math.max(neighbors.length,1)-Math.PI/2;pos.set(i,[450+320*Math.cos(a),240+175*Math.sin(a)])});let svg='<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z" fill="#839fa4"/></marker></defs>';const links=new Set();for(const j of activeEdges){const e=G.edges[j];if(!pos.has(e.s)||!pos.has(e.t)||e.s===e.t)continue;const key=e.s+':'+e.t;if(links.has(key))continue;links.add(key);let [x,y]=pos.get(e.s),[u,v]=pos.get(e.t);const len=Math.hypot(u-x,v-y),dx=(u-x)/len,dy=(v-y)/len;svg+='<line class="edge" x1="'+(x+dx*15)+'" y1="'+(y+dy*15)+'" x2="'+(u-dx*19)+'" y2="'+(v-dy*19)+'" marker-end="url(#arrow)"/>';}for(const [i,[x,y]]of pos){const n=G.nodes[i],label=n.label.length>28?n.label.slice(0,26)+'…':n.label;svg+='<g tabindex="0" role="button" aria-label="'+esc(n.label)+'" class="node '+(i===selected?'selected':'')+'" data-node="'+i+'"><title>'+esc(n.label)+'</title><circle cx="'+x+'" cy="'+y+'" r="'+(i===selected?15:10)+'"/><text x="'+x+'" y="'+(y+28)+'" text-anchor="middle">'+esc(label)+'</text></g>'}$('diagram').innerHTML=svg;$('diagram').querySelectorAll('.node').forEach(el=>{el.onclick=()=>selectNode(Number(el.dataset.node));el.onkeydown=e=>{if(e.key==='Enter')el.onclick()}});$('diagramNote').textContent='当前范围 '+activeEdges.length+' 条主张；显示 '+neighbors.length+' / '+[...counts.keys()].filter(i=>i!==selected).length+' 个邻居。点击节点可继续查看；箭头上的多条主张在下方分别保留。';}
function renderEdges(){$('edgeHeading').textContent='原始关系与证据 · '+activeEdges.length+' 条';$('edges').innerHTML=activeEdges.slice(0,shown).map(j=>{const e=G.edges[j],doi=e.doi?'<a target="_blank" rel="noreferrer" href="https://doi.org/'+encodeURIComponent(e.doi.replace(/^https?:\/\/(dx\.)?doi\.org\//i,''))+'">DOI</a>':'';return '<details><summary>'+esc(e.subject)+' <strong>'+esc(e.p)+'</strong> '+esc(e.object)+'<br><small>'+esc(e.paper)+' · '+esc(e.year)+' · '+esc(e.assertion)+' · '+esc(e.review)+'</small></summary><div class="detail"><p>'+esc(e.title)+' '+doi+'</p><p>条件：'+esc(e.conditions||'未说明')+'<br>共同因素：'+esc(e.joint.join('；')||'未说明')+'<br>证据类型：'+esc(e.modality)+' · 范围：'+esc(e.scope)+'<br>主张归属：'+esc(e.claim_scope)+' · 文献类型：'+esc(e.article_role)+'</p>'+e.q.map(q=>'<blockquote>'+esc(DATA.quotes[q])+'</blockquote>').join('')+'<small>原始主张编号：'+esc(e.id)+'</small></div></details>'}).join('');$('more').hidden=shown>=activeEdges.length;}
async function start(){try{const binary=atob($('payload').textContent.trim());const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));DATA=JSON.parse(await new Response(stream).text());$('loading').hidden=true;$('app').hidden=false;const params=new URLSearchParams(location.search);if(['iTE','TG'].includes(params.get('domain')))$('domain').value=params.get('domain');setDomain();const cid=params.get('node');if(cid){const n=G.nodes.findIndex(x=>x.concept_id===cid);if(n>=0)selectNode(n)}$('domain').onchange=setDomain;$('search').oninput=search;$('scope').onchange=()=>selectNode(selected);$('top').onclick=()=>{$('search').value='';search();selectNode(sortedNodes()[0])};$('more').onclick=()=>{shown+=40;renderEdges()};window.graphExplorerReady=true;}catch(e){$('loading').className='loading error';$('loading').textContent='无法加载查看器：'+e.message+'。请使用近期版本浏览器；原始数据仍可从同目录 JSON/GraphML/CSV 读取。';}}
start();
</script></html>'''

if __name__=='__main__': build_viewer()
