from audit import judge
judge(180,'supported','形变减小阻挡电阻，明确中间关系。',scope='application_sensing')
judge(181,'supported','二元溶剂弱化水水氢键，原文直接陈述；不补造未给出的溶剂身份。')
judge(182,'supported','电荷转移配合物形成解释混合物协同性能，归因准确。')
judge(183,'supported','适量水维持共晶性质，修饰词适量没有丢失。')
judge(184,'supported','整体多层薄膜减少热损失，整体设计主语可承载多因素。',scope='device_engineering')
judge(185,'supported','适量水提高redox盐溶解度，can与范围完整。')
judge(186,'supported','SWNT涂层提高输出有直接支持；原文conductance用词可疑但此边未据此构造电导方向。')
judge(187,'supported','两种腐蚀共同可提高总损失2–7倍，未将局部损伤一律强化。',scope='corrosion_electrodeposition')
judge(188,'supported','redox动力学影响电压，没有把未给定的单调方向补上。',scope='application_sensing')
judge(189,'supported','水平池扩散迁移用于浓度分布模型，analytical/modeling范围明确。','analytical_model',scope='measurement_method_model')
judge(190,'supported','混合结构同时改善应力/断裂形变，联合材料主语与结果完整。')
judge(191,'supported','传氢离子与电势耦合系数为实验测得关联，不误升单向因果。','experiment_with_NET',scope='thermodynamics')
judge(192,'qualify','压阻与热电协同才构成自供能手势转导，需要共同因素绑定。',scope='application_sensing',joint='thermoelectricity + active piezoresistivity',repair='添加共同因素组并保持体热和应变条件。')
judge(193,'supported','非共价交联支持紧密物理电接触，明确结构关系。',scope='device_engineering')
judge(194,'supported','工作中调物态切换主导阳/阴离子，p/n可逆范围与原文一致。')
judge(195,'supported','Seebeck不是Soret存在的必要条件，not required准确；未误否定Soret可影响Seebeck。',scope='thermodynamics')
judge(196,'supported','水凝胶扰动第一壳明确标simulation，不冒充实验。','computational_prediction')
judge(197,'supported','归一化四价离子浓度梯度增加Seebeck，原文支持该链条。')
judge(198,'supported','高比表面积/体积对应较高热阻，为本文形状对照的作者归因，不外推普适律。',scope='device_engineering')
judge(199,'supported','Li水配位抑冰解释明确标simulation supports，非独立实验因果。','computational_prediction')
