from audit import judge
judge(160,'supported','GO诱导四价阴离子结晶增强TG效应，具体物种准确。')
judge(161,'supported','上层吸光功能明确。',scope='device_engineering')
judge(162,'supported','对流增强传质与同时降低温差不矛盾；此边未称净功率提高。')
judge(163,'supported','DMSO/EG氢键抑制结晶，与原句一致。')
judge(164,'supported','乙二醇换溶剂促进热电势保持，结果与条件明确。')
judge(165,'supported','纳米胶热捕冷放I3顺序完整。')
judge(166,'qualify','原文组合设计产出高强度，不能将拉伸结晶单独立为已分离验证的原因。',scope='device_engineering',joint='stretching-induced crystallization + thermoelectric-effect integrated design',repair='改为组合设计与高强度的属性关系，保留19MPa。')
judge(167,'supported','粒子浓度、场强和方向对模型参数的依赖完整保留。','analytical_model',scope='thermodynamics')
judge(168,'supported','would与特定乙醇含量限定正确，假说未变成确定结论。')
judge(169,'supported','压缩循环后纳米线接触连接改善归因准确；属于电子TE外围，不当TG机制。',scope='other_adjacent_domain')
judge(170,'qualify','intentionally utilized to明确设计目的，摘要未直接验证壳重排，需目的性表述。',repair='谓词改为intentionally used to modulate，模态design_purpose。')
judge(171,'supported','非对称电极对两端反应的特异催化是明确作者陈述。')
judge(172,'supported','熵差增加提升thermopower，DES背景可溯源。')
judge(173,'supported','以负值绝对量增大表达而非代数值增加，物理符号正确。')
judge(174,'supported','电泳电荷数只是分析模型参数，未外推因果促进方向。','analytical_model',scope='thermodynamics')
judge(175,'supported','仅合适低介电大体积溶剂条件下电荷可加性提升熵驱动过程，only限定保留。')
judge(176,'supported','could/suggested前景以hypothesis保留，100–150°C范围在证据。',scope='device_engineering')
judge(177,'supported','三组分多氢键支持10天电性能保持，作者归因明确。')
judge(178,'supported','纯冰结相时浓缩增E，未与水合盐结相时减E混淆。')
judge(179,'supported','光吸收转热的过程关系可读，层间光热机制准确。',scope='device_engineering')
