from audit import judge
judge(0,'qualify','因果与联合振动来源正确，但原关系未标识DFT证据。','computational_prediction',repair='保留原三元组，增加DFT计算来源限定。')
judge(1,'supported','Na离子与CNT羧基相互作用促进离子电导，与作者原话一致。')
judge(2,'supported','改进CVT须配适当热处理，条件与单晶产物完整。',scope='synthesis_processing')
judge(3,'supported','DMSO诱导的长PEDOT互联网络提高电导，处理条件明确。')
judge(4,'supported','移除绝缘PSS促进电导的作者机制表达得到直接支持。')
judge(5,'supported','应变改善ZT方向正确，谓词已标in calculation。','computational_prediction')
judge(6,'qualify','散射增多—平均自由程缩短—晶格热导下降方向正确，缺计算来源标记。','computational_prediction',repair='增加第一性原理计算限定。')
judge(7,'supported','实验比较离子风的冷却性能成立，属于热管理设备。',scope='thermal_management')
judge(8,'supported','半径减小与热电势增大共变，association准确。')
judge(9,'supported','缺陷偶极限制极化的陈述明确。',scope='other_adjacent_domain')
judge(10,'supported','geopolymer热电行为的离子起源为作者归因，未虚构详细微观机理。')
judge(11,'qualify','Mg增加削弱多数键的计算结果，需保留计算来源。','computational_prediction',repair='增加第一性原理计算限定。')
judge(12,'supported','非谐与无序作为联合主语，特定Cu主导准粒子而非全部声子崩溃，范围准确。','experiment_and_computation')
judge(13,'supported','化学差异抗反位形成作为设计依据，以hypothesis保守保留。',scope='other_adjacent_domain')
judge(14,'supported','否定的是单靠层向简单预测弹性各向异性，并非否定关联。',scope='other_adjacent_domain')
judge(15,'supported','两种材料与两个直隙值按respectively对应，并标calculated。','computational_prediction',scope='other_adjacent_domain')
judge(16,'supported','否定点缺陷散射占主导，并未否定存在散射，符合Umklapp仍占主导的原句。')
judge(17,'qualify','谓词写明共同因素，但须机器可读绑定外场、矢量电荷转移和梯度能带三个因素。',scope='other_adjacent_domain',joint='external electric field + vector charge transfer + gradient energy band',repair='登记联合因素组，禁止单因素独立支持解释。')
judge(18,'supported','是否发生界面电化学决定增强持续时间，没有假定单调增强方向。')
judge(19,'supported','bisulfate作为热扩散阴离子载流子是材料功能关系，作者原文明确。')
