from audit import judge
judge(40,'supported','凝胶结构提供加速离子输运通道；该中间关系有直接支持。')
judge(41,'qualify','温度升高热导下降的关联正确，缺少第一性原理/Boltzmann计算模态。','computational_prediction',repair='加入计算来源限定。')
judge(42,'supported','Ti/Zr质量与尺寸差异散射主导降热导，以suggest/hypothesis保留推测强度。')
judge(43,'qualify','温差驱动的i-TE须与NERD协同，独立温差到双性能边需要联合约束。',scope='device_engineering',joint='i-TE conversion + NERD',repair='联合因素绑定；温差作为i-TE驱动条件。')
judge(44,'supported','mobile hopping引起密度涨落，谓词in model明确理论范围。','computational_prediction')
judge(45,'supported','锂盐在产物中充当导电组分，功能关系被原句直接支持。')
judge(46,'qualify','原文是通过侧链位置有效控制离子运动来改善PF，不是无条件离子运动就改善。',repair='主语改为effective control of free-ion movement by zwitterionic side-chain moiety positions。')
judge(47,'supported','固定表面电荷密度增加促进温度梯度下输运，方向与条件均有支持。')
judge(48,'supported','graphene桥结构could改善交换电流密度，假说强度保留。')
judge(49,'supported','结构对称性提高时同载流子浓度范围内迁移率相近，未错写为提高。')
judge(50,'supported','2DEG性能高于bulkZnO是明确比较。','experiment_and_computation')
judge(51,'supported','较大阴离子引入降低有序无序转变温度，原文材料范围可追溯。')
judge(52,'supported','apoplast阴离子热扩散导致热电响应，叶片条件可定位。')
judge(53,'supported','定向纳米通道离子流用于热电转换，功能表述准确。',scope='device_engineering')
judge(54,'supported','抑制Se蒸气允许化学计量精确控制，原文owing to支持。',scope='synthesis_processing')
judge(55,'supported','MXene促进结合水到中间水的转化，水状态与材料明确。')
judge(56,'qualify','联合主语完整，但第一性原理晶格动力学/Boltzmann计算需显式标注。','computational_prediction',repair='增加计算证据模态。')
judge(57,'supported','对离子性质控制颗粒热扩散正负方向，未推断哪个离子对应哪个方向。')
judge(58,'supported','半金属性是计算表征，谓词calculated明确。','computational_prediction',scope='other_adjacent_domain')
judge(59,'supported','离子热扩散电场下电子/空穴漂移形成外电路电流，条件在证据句完整。')
