from audit import judge
judge(140,'supported','this phenomenon回指低温运行及力学表现，shared attribution保留，未拆分共同原因。')
judge(141,'supported','热端捕获冷端释放形成自由I3浓度梯度，冷热方向准确。')
judge(142,'supported','溶解度参数合适的有机溶剂使溶剂化壳重排，必要修饰词保留。')
judge(143,'qualify','高可达面积与快电子转移共同提升电流及效率，需联合绑定。',joint='high electrochemically accessible surface area + fast redox-mediated electron transfer',repair='增加共同因素组。')
judge(144,'supported','实验显示两液温差诱导电极redox，引用虽含模拟但该结论有明确实验支持。')
judge(145,'supported','选择输运使HQ积于冷电极，物种与空间方向准确。')
judge(146,'supported','离子对重排解释大温度系数，保留作者归因且不把负值变成正值。')
judge(147,'qualify','高丙酮比第一壳插入提高热电势来自MD，需显式计算限定并展开a定义。','computational_prediction',repair='加入MD预测标记；宾语为thermogalvanic temperature coefficient alpha of Fe3+/Fe2+。')
judge(148,'qualify','源文是high Seebeck coefficient支持灵敏转导，裸量名遗漏高值限定。',scope='application_sensing',repair='主语改为high Seebeck coefficient。')
judge(149,'supported','四组分相互作用联合主语完整，相对纯PAAm改善力学表现。')
judge(150,'supported','DMSO水氢键支持低温连续实验运行，>-20°C条件在证据明确。')
judge(151,'supported','引入浓度梯度增强输出是实测陈述，不宣称全部输出源于热转换。')
judge(152,'qualify','蒸馏和温度依赖溶解度两个因素共同维持浓度差，hypothesis正确但缺共同因素。','theoretical_proposal',scope='thermodynamics',joint='temperature-gradient distillation + temperature-dependent NaOH solubility',repair='增加联合因素组。')
judge(153,'supported','配合物解离提高离子动力学的方向直接支持；混流条件保留。')
judge(154,'supported','CsCl通过改变溶剂化提高Seebeck，未把电流增强机制混进此边。')
judge(155,'supported','高氯酸根不配位抑制离子对形成，极性方向正确。')
judge(156,'supported','盐水浓差渗透发电成立，但属于渗透发电外围，不是TG固有机制。',scope='other_adjacent_domain')
judge(157,'supported','太阳蒸发产生浓盐水，过程关系准确，属于外围领域。',scope='other_adjacent_domain')
judge(158,'supported','redox构象熵变化导致作者定义n型热电势，保留负号约定。')
judge(159,'supported','分层隔开redox物种使浓度梯度可控，未推断方向。',scope='device_engineering')
