from audit import judge
judge(100,'supported','Au复合膜LSPR性质是原文明确的组成贡献。',scope='device_engineering')
judge(101,'supported','可逆键提供耗能，双交联来源在同句明确。')
judge(102,'supported','铁氧化伴随铁磁化合物形成，为磁测分析所报告的结果，不另推具体物种。',scope='other_adjacent_domain')
judge(103,'supported','DFT特征与Seebeck预测关联准确，未升级成因果。','model_association',scope='measurement_method_model')
judge(104,'supported','凝胶减薄消除像素串扰，原文明确。',scope='application_sensing')
judge(105,'supported','原位氧化还原维持电极附近浓度梯度，方向无误。')
judge(106,'supported','水和热吸收共同诱导Na/H解离扩散，联合因素与结果完整。')
judge(107,'supported','ZnAl-LDH选择结合四价阴离子，未误作三价。')
judge(108,'supported','水凝胶中离子对应热电化学循环，未与水气化循环混淆。',scope='device_engineering')
judge(109,'supported','NHPC连续结构缩短电解质离子扩散路径，明确直接。')
judge(110,'qualify','孔结构与氮掺杂共同贡献，且仅800°C条件下最大值；需要联合组。',joint='well-developed pore structure + nitrogen doping',repair='绑定共同因素并保持800°C碳化条件。')
judge(111,'supported','界面效应可促进输运，can未改成定量或普适保证。')
judge(112,'supported','NiO比锂化NiO稳定，负Seebeckabove原文保持，不擅自解释绝对值。',scope='device_engineering')
judge(113,'supported','quasi-stable water-in-salt区比salt-in-water功率下降，条件与方向明确。')
judge(114,'supported','improves as source wording未擅改成电阻增或减；方向未给定，不用于方向性推理。')
judge(115,'supported','盐析导致微纳通道内离子输运受限，原文明确。')
judge(116,'supported','光热转换建立温差，器件布局是证据上下文。',scope='device_engineering')
judge(117,'supported','浓度依赖不等于单调增减，association保留原文未指定方向。')
judge(118,'qualify','低激光功率下沉积主导是竞争过程解释，需保留can be interpreted模态。',scope='corrosion_electrodeposition',repair='谓词改为interpreted as predominant deposition contribution at lower laser power。')
judge(119,'supported','明确authors report，不把量子能量机制的作者概括当独立实证确认；无Faradaic条件保留。',scope='other_adjacent_domain')
