from audit import judge
judge(120,'supported','快冷通过抑晶等步骤促进氧化还原，直接链条未外推独立量值。')
judge(121,'supported','随皮肤形变贴合支持人体热采集，器件功能明确。',scope='device_engineering')
judge(122,'supported','promising strategy标hypothesis准确，未把展望当实测。',scope='device_engineering')
judge(123,'supported','离子扩散率差导致双电层界面不对称，是作者解释。')
judge(124,'supported','NaK合金熔融相变提升热电势，电极相变范围明确。')
judge(125,'supported','Li水合结构支持抗冻，原句直接支持。')
judge(126,'qualify','间距优化与浓度优化共同改善性能，应绑定而非单因素推断。',scope='device_engineering',joint='redox-couple concentration optimization + hot/cold electrode separation optimization',repair='加入联合因素组。')
judge(127,'supported','高温降低点蚀电位，Alloy31/LiBr范围由证据限制。',scope='corrosion_electrodeposition')
judge(128,'supported','自然对流增强传热不等于提升净发电；此边只讲传热，原文支持。')
judge(129,'supported','MXene空心微球提升电化学活性面积，明确中间结构关系。')
judge(130,'supported','协同输运使TGC/RED相互增益，耦合限定已保留。',scope='device_engineering')
judge(131,'supported','Fe3与水作用提高氧化还原溶剂化熵，在流动混合/配合物解离上下文成立。')
judge(132,'supported','cold-above-hot有利对流下传质不限制电流，否定范围明确。')
judge(133,'supported','外循环间周期交换介体实现连续脱盐，条件明确。',scope='device_engineering')
judge(134,'supported','仅studied的研究对象关联，不作温差增加腐蚀的因果边。','experiment_and_computation',scope='corrosion_electrodeposition')
judge(135,'qualify','高功率腐蚀减少净沉积是竞争解释，需解释性模态。',scope='corrosion_electrodeposition',repair='谓词改为interpreted competing dissolution contribution reducing net deposition at high laser power。')
judge(136,'qualify','热电化学与电化学电势共同贡献电压，不可全归热驱动，原文仅约33%热贡献。',scope='device_engineering',joint='thermogalvanic effect + electrochemical potential',repair='绑定联合来源，保留90°C约33%热贡献及无空间温差条件。')
judge(137,'qualify','活性位点与3D骨架及高电导共同解释性能，单项不可独立。',joint='3D skeleton + abundant electroactive sites + high conductivity',repair='绑定三因素。')
judge(138,'supported','离子对降低Seebeck，与抑制离子对提高性能没有方向倒置。')
judge(139,'supported','转速改变时电荷转移电阻无观察到依赖，与扩散电阻下降区别正确。')
