from audit import judge
judge(20,'supported','光致热电场驱动颗粒紧密组装，原文直接支持。',scope='other_adjacent_domain')
judge(21,'supported','受限微区短程热扩散产生串联累积的局部热电压，结构与条件明确。')
judge(22,'supported','载流子浓度升高导致电导增加，Pb掺杂上下文可定位。')
judge(23,'qualify','需要记录计算模态以及群速度/本征结构各向异性联合因素。','computational_prediction',joint='anisotropic phonon group velocity + intrinsic structure anisotropy',repair='增加计算限定及联合因素组。')
judge(24,'qualify','较弱Sr-O键与较大过剩体积共同解释界面热导低，单边不可独立解读。',joint='higher excess volume + weaker Sr-O bonds',repair='联合因素绑定并保留SrO-rich对TiO2-rich边界比较。')
judge(25,'supported','热扩散与Seebeck两效应完整放入联合主语，连续产电是作者结论。',scope='device_engineering')
judge(26,'qualify','these complexes须跨句解析为混合八面体-四面体[TS4]Cu6配合物。','experiment_and_computation',repair='主语展开为interactions between mixed octahedral-tetrahedral [TS4]Cu6 complexes；附前一句证据。')
judge(27,'supported','所有Ni含量均被抑制，未误称浓度单调关系；4K<T<35K条件保留于证据。')
judge(28,'supported','大气湿度增加时电导上升，水合上下文支持association。')
judge(29,'qualify','alpha在局部引文未定义，全文定义为electrochemical Seebeck coefficient，需显式展开。',repair='宾语展开为electrochemical Seebeck coefficient alpha；保留OH−/H2O alternatives和作者解释。')
judge(30,'supported','正Seebeck与阳离子冷到热迁移是作者符号约定，谓词as reported已避免改写成普适方向。')
judge(31,'supported','Ca交联增强BC气凝胶力学稳健性，相比pristine基线明确。')
judge(32,'supported','退火后电导出现属于观测关联，未声称温度单调增加。')
judge(33,'supported','材料可具有高热电压的属性陈述，不外推数值或机制。')
judge(34,'supported','Sr/Zn取代引起无序压低总热导，保留total而非擅改lattice。')
judge(35,'supported','文献最大值限定为作者当时open literature和carbon-based集合；不用于当前排名。',scope='reported_performance_context')
judge(36,'supported','超过140°C退火引起网络形成及离子到电子主导转变，方向与阈值保留。')
judge(37,'supported','SA-Ca交联同时增强阻燃和强度，联合结果完整。',scope='application_sensing')
judge(38,'supported','保守influences保留声子域散射影响拖曳效应，全文支持。')
judge(39,'qualify','光聚合须与氢键网络共同固定阳离子，jointly文字不足以绑定两因素。',joint='photo-polymerization + hydrogen-bonding networks',repair='联合因素绑定。')
