from audit import judge
judge(60,'qualify','半径差产生应变场为模型结果，需要模型来源限定。','computational_prediction',repair='补充model calculations限定。')
judge(61,'supported','复合相变材料减少间歇温度波动，15min周期及比较数据可追溯。',scope='thermal_management')
judge(62,'qualify','n载流子优化与新增Cu离子传导联合解释掺杂效果，推测模态正确但联合绑定缺失。',joint='additional Cu ion conduction + optimization of n-type carrier density',repair='添加联合因素组，保持hypothesis。')
judge(63,'supported','金属与聚合物结合导致Cl通道形成，为明确作者机制。')
judge(64,'supported','probably not保留不确定的否定判断，没有删去少见跃迁仍存在这一事实。')
judge(65,'supported','annealed填料对应n型，未与pristine对应p型混淆。')
judge(66,'supported','压电产生内场增强离子热电势，PE定义已从摘要核实。')
judge(67,'supported','阴离子有序稳定HT结构，this指前句有序，指代可解析。')
judge(68,'qualify','多尺度结构与键软化共同降晶格热导，单独拆边需联合约束。',joint='bond softening + multiscale hierarchical structures',repair='绑定共同因素。')
judge(69,'qualify','高掺杂与高结构有序共同改善电导，不能删掉结构有序条件。',joint='high doping level + high structural order',repair='绑定共同因素。')
judge(70,'qualify','共价网络、电极依赖与离子尺寸差条件共同造成浓度差，单边需约束。',joint='covalent cross-linked polymer network + electrode-dependent effect under ion-size difference',repair='绑定因素并保留热扩散与尺寸差条件。')
judge(71,'supported','DFT解释水含量4:1下弱化阴离子簇/Au作用引起p-n转变，模态与条件正确。','computational_prediction')
judge(72,'supported','稀释纳米纤维素水凝胶改善织物耐磨损，摘要明确。',scope='device_engineering')
judge(73,'supported','Y掺入抑制烧结晶粒生长，与原文一致。',scope='synthesis_processing')
judge(74,'supported','Ga-Sb共价性质明确标注计算，块内键范围保留。','computational_prediction')
judge(75,'supported','否定去掺杂导致S上升，替代DOS解释未被误当否定对象。')
judge(76,'supported','缺陷结构支配三种输运量，属通用理论背景，保持范围。',scope='thermodynamics')
judge(77,'supported','两种聚合物体系的空气稳定性改善和40%RH条件准确。')
judge(78,'supported','La取代/氧空位产生载流子的共同来源完整保留，增电导为作者归因。')
judge(79,'supported','含SnO2掺杂样品比未掺杂样品热导更高，比较对象和方向正确。')
