from audit import judge
judge(80,'supported','按作者补偿机制产生电子归因保留；不由Ca价态自行推导反向结论。','experiment_and_computation')
judge(81,'supported','否定不相容因子材料的高效分段组合，未推广到所有结构组合。',scope='thermodynamics')
judge(82,'supported','明确绝对值随半径增加而下降，正负符号未混淆。')
judge(83,'supported','阳离子交换抑制TDAE扩散相关去掺杂，宾语机制保留。')
judge(84,'supported','升温热还原导致空穴减少，气氛与材料范围在证据完整。')
judge(85,'supported','Li增加导致空穴密度增强，正向链条可直接读出。')
judge(86,'qualify','PSS分离与PEDOT构象改变共同解释电导增强，需绑定联合因素。',joint='PSS separation + benzoid-to-quinoid PEDOT conformational change',repair='建立共同因素组。')
judge(87,'supported','碘占优对应室温储存分解最快，association没有把趋势写成必然反应。')
judge(88,'supported','5–10%Sr和1%O2条件明确，未线性外推至20%。')
judge(89,'supported','Mn-O-Mn弯曲引起带宽窄化，Ca取代条件与作者解释保持一致。')
judge(90,'qualify','弱离子键导致声学软化的计算机制，缺显式计算标记。','computational_prediction',repair='增加first-principles/Boltzmann证据模态。')
judge(91,'qualify','Cu非谐各向异振动、Cu周围离子键、全局弱键共同解释类玻璃热性质，必须绑定。',joint='anharmonic anisotropic Cu vibration + ionic bonds around Cu + global weak bonding',repair='建立三因素联合组。')
judge(92,'supported','电子声子散射增强降低电导，是often限定的解释，不当作所有材料普适实测。',scope='thermodynamics')
judge(93,'supported','Bi掺杂与晶格膨胀共变，association未把较小Bi半径误当膨胀机理。')
judge(94,'qualify','used to enhance为制备目的，摘要未给添加前后对照，不能标为已实测因果增益。',scope='device_engineering',repair='谓词改为used with aim of enhancing；标design_purpose。')
judge(95,'qualify','混合导电只是电子/离子Seebeck联合设计一环；三参数需展开为P/T/H。',scope='application_sensing',joint='electronic Seebeck effect + ionic Seebeck effect + mixed ion-electron conduction in elastic aerogel',repair='绑定联合机制，并展开宾语为pressure-temperature-humidity readout with minimal crosstalk。')
judge(96,'qualify','3:1对1:1比较有效，但源自三维瞬态模拟，不是实验测得。','computational_prediction',scope='thermal_management',repair='补充numerical-model预测限定。')
judge(97,'supported','may与proposed保留组分调整的展望性质。')
judge(98,'supported','温度与生长时间联合调控直径，联合主语保留。',scope='synthesis_processing')
judge(99,'supported','may保留假设强度，键增强与阻挡层均在联合主语中。')
