from work import core
core(0,[
('coherent electron and heat transport through a pointlike contact','produces','atomic Seebeck effect','Here we show that coherent electron and heat transport through a pointlike contact produces an atomic Seebeck effect, which is described by the mesoscopic Seebeck coefficient multiplied by an effective temperature drop at the interface.','author_claim'),
('logarithmic energy derivative of local density of states at Fermi energy','approximately proportional to','mesoscopic Seebeck coefficient','The mesoscopic Seebeck coefficient is approximately proportional to the logarithmic energy derivative of local density of states at the Fermi energy.','association'),
('atom-to-atom interaction at interface','may control','effective temperature drop at tip-sample junction','We deduced that the effective temperature drop at the tip-sample junction could vary at a subangstrom scale depending on atom-to-atom interaction at the interface.','deduced_may')],scope='measurement_method_model')
core(1,[
('copper-coordinated carboxylated cellulose','enhances','thermal-gradient diffusion of CuCl4(2-) complexes','Here, we demonstrate a hydrated polyvinyl alcohol (PVA)-cellulosic membrane that relies on the thermal gradient diffusion of transition metal and chloride complexe [CuCl4](2-) enhanced by copper-coordinated carboxylated cellulose.','author_claim'),
('highly-coordinated Cu2+-Cl- configuration via carboxylated cellulose','raises ion transport heat and enhances','thermally generated voltage','We attribute the enhanced thermally generated voltage to the highly-coordinated configuration of Cu2+ - Cl-, which converts the independent thermal motion of Cu2+ and Cl- to the higher ion transport heat of [CuCl4](2-) anion via carboxylated cellulose, while this phenomenon do not occur in the other transition metal chlorides.','author_attribution'),
('other transition metal chlorides','do not exhibit','same specific enhanced heat-transport phenomenon','while this phenomenon do not occur in the other transition metal chlorides.','negated')])
core(2,[
('C and N doping in CsZnCl3','changes','semiconductor to spin-semiconductor nature','Interestingly, the doping turns out from semiconducting to spin semiconducting nature.','computational_prediction'),
('C and N doping in CsZnCl3','increases','figure of merit from 0.79 to almost 1.0','The figure of merit for CsZnCl3 is calculated to be 0.79 and increases to almost 1.0 with the doping of C and N.','computational_prediction')])
core(3,[
('high-temperature disorder and onset of superionic conductivity','produce little further reduction in','lattice thermal conductivity','Little reduction in lattice thermal conductivity was observed in the high-temperature phase, despite the increased disorder on the cation site and the onset of superionic conductivity.','observed_limited_effect'),
('anharmonic bonding and diffuson dominated transport','suggested joint origin of','inherently low lattice thermal conductivity in ACrX2','This suggests that the low lattice thermal conductivity in ACrX2 compounds is an inherent property of the crystal structure, caused by anharmonic bonding and diffuson dominated transport.','suggested_joint')],reason='聚焦本研究热输运结论，不把引言泛化机制再计为独立核心关系。')
core(4,[
('ionic bonding character and large Born effective charges','jointly cause','colossal phonon-electric field coupling','It is driven by the colossal phonon-electric field coupling arising from the domination of ionic character in the interatomic bonds and Born effective or dynamical charges as high as 7.4e on the Hf ions, which is seven times that on Mo in MoS2 single layer.','computational_joint'),
('colossal phonon-electric field coupling','drives','large LO-TO splitting','It is driven by the colossal phonon-electric field coupling','computational_prediction'),
('including non-analytic correction','increases calculated','lattice thermal conductivity','Enhancement in k(L) occurs in HfS2 (2.19 to 4.1 W m(-1) K-1), HfSe2 (1.23 to 1.7 W m(-1) K-1) and HfSSe (1.78 to 2.2 W m(-1) K-1) upon the incorporation of the non-analytic correction term.','computational_prediction'),
('large mass, low velocities, Debye temperature, stiffness, lifetimes, heat capacity and strong anharmonicity','collectively explain','low lattice thermal conductivity','Large atomic mass of Hf (178.5 u), small phonon group velocities (4-5 km s(-1)), low Debye temperature (similar to 166 K), low bond and elastic stiffness (Young\'s modulus similar to 75 N m(-1)), small phonon lifetimes (similar to 6 ps), low specific heat capacity (similar to 17 J K-1 mol(-1)) and strong anharmonicity are collectively found to be the factors responsible for such a low k(L).','computational_joint')])
core(5,[
('cation coordination with PEO ether oxygen','controls','cation-anion diffusion coefficients and Eastman entropy changes','Through precise control of cationanion diffusion coefficients and Eastman entropy changes, the high-performance n-type solid-state i-TE materials are obtained.','author_claim'),
('divalent Mg2+/Zn2+ versus monovalent Li+/Na+ at X/EO=0.15','enhances','thermopower with larger entropy and diffusivity differences','The MD simulations reveal that divalent cations (Mg2+ and Zn2+) outperform monovalent cations (Li+ and Na+) in enhancing thermopower, exhibiting larger entropy changes and diffusivity differences at an X/EO ratio of 0.15.','simulation_and_comparison'),
('PEO/MgTFSI2 versus PEO/LiTFSI','has larger magnitude','negative thermopower','Furthermore, experimental results show that the thermopower of divalent composite of PEO/MgTFSI2 (-6.18 mV K- 1) is significantly higher than that of monovalent PEO/LiTFSI (-1.6 mV K- 1).','observed_comparison')])
core(6,[
('electronic band structure and DOS','suggest','metallic WB and semimetal-like WAlB','The band structure and density of states around the fermi level suggest that WB has a metallic nature and WAlB has a semimetal-like character.','computational_inference'),
('large infrared reflectivity','suggests suitability for','coating to remove solar heating','The larger reflectivity in the low-energy region (infrared) indicates that these materials can be used as a coating material to remove solar heating.','potential_application')],reason='保留结构/输运识别及热管理用途的核心关系；高PF/高热导的泛泛应用评价不再扩作机制。',scope='measurement_method_model')
core(7,[
('thermal activation of intrinsic localized modes','enhances and makes anisotropic/inhomogeneous','thermal expansion','With the thermal activation of ILMs, thermal expansion is enhanced, made more anisotropic, and, at a microscopic level, becomes inhomogeneous','author_claim'),
('ILM activation','suppresses','lattice thermal conductivity','The lattice thermal conductivity is suppressed at the ILM activation temperature, while no impact is observed in the electrical conductivity.','author_claim'),
('ILM activation','has no observed impact on','electrical conductivity','The lattice thermal conductivity is suppressed at the ILM activation temperature, while no impact is observed in the electrical conductivity.','negated'),
('complement of transport effects from ILMs','could improve','thermoelectric performance','This complement of transport properties suggests that ILMs could improve thermoelectric performance','suggested_could')],reason='以ILM与热/电输运为核心，未把辐照损伤、孔洞、断裂等并列相邻议题计入热电核心分母。')
