from work import core
core(24,[
('combining p-CuI and n-ZnO:In thin-film thermolegs','proposed to enable','near-infrared solar thermoelectric generation near room temperature','The possibility of combining of the obtained p-CuI and n-ZnO:In thin film thermolegs into a thermocouple is shown for the use in new semitransparent planar solar thermoelectric generator working at near-room temperatures through harvesting near-infrared solar light as an energy source to supply electric power to the wireless sensors and microscale devices.','demonstrated_possibility')],scope='device_engineering')
core(25,[
('PAA/PEO with sodium dihydrogen phosphate one-pot photopolymerization','forms','hydrogen-bonded ionic hydrogel network','Through a simple one-pot photopolymerization process, polyacrylic acid (PAA) and polyethylene glycol (PEO) were combined with sodium dihydrogen phosphate (SDP) to form a robust hydrogen-bonded ionic hydrogel network.','joint_design'),
('phosphorus salt incorporation','enhances','flame retardancy and encapsulated-wood oxygen index','The incorporation of the phosphorus salt enhanced flame retardancy to reach the UL-94 V-0 rating and significantly increased the oxygen index of encapsulated wood from 27% to 54%.','observed_joint_outcome'),
('fire exposure of hydrogel warning device','rapidly generates','about50mV voltage within1.5s','Moreover, as a fire-warning device, it could rapidly generate an output voltage of ca. 50 mV within 1.5 s upon exposure to fire, showcasing potential for autonomous fire prevention systems.','reported_function')],scope='application_sensing')
core(26,[
('1M LiBF4/3-MPN permeation in Sb-SnO2 porous film','decreases resistivity without significant change in','Seebeck coefficient','A 61.9% average decrease in the electrical resistivity without a significant variation of the Seebeck coefficient was found in the case of 1 M LiBF4 in 3-MPN.','observed_joint_outcome'),
('BMII electrolyte permeation','reduces resistivity and Seebeck magnitude with net enhancement of','power factor','Using the BMII ionic liquid, the electrical resistivity showed a more significant average decrease of 82.5%; however, the absolute value of the Seebeck coefficient was reduced by 35%, finally resulting in an average enhancement of 2.4 times of the PF.','observed_joint_outcome'),
('ions modifying solid-liquid-interface electrostatic environment','attributed cause of','large power-factor enhancements','The large enhancements achieved are attributed to the modification of the electrostatic environment of the porous solid by the ions in the electrolyte at the solid-liquid interface.','author_attribution')],scope='device_engineering')
core(27,[
('1-ethyl-3-methylimidazolium chloride','promotes','hexagonal BN exfoliation into nanosheets','Ionic liquid 1-Ethyl-3-methylimidazolium chloride was employed to promote the exfoliation of hexagonal boron nitride (BN) to fabricate the boron nitride nanosheets (BNNSs).','author_claim'),
('2D filler structure and enhanced filler-matrix interaction','jointly support','mechanical properties, thermal conductivity and storage modulus','The developed material was provided with superior mechanical properties, satisfied thermal conductivity and strong storage modulus attributing to the two-dimensional structure of the filler and the enhanced interfacial interaction between the filler and matrix.','joint_attribution')],scope='thermal_management')
core(28,[
('phonon-mode participation in atomic jumps, especially short wavelengths','determines in model','relationship between heat of transport Q and activation energy Ea','We have shown that the relationship between Q and E-a is determined by the participation degree of different phonon modes, in particular the short wavelength phonons to the atomic jump processes.','model_result'),
('increasing Q/Ea','suggests increased','degree of collective ionic motion','it is suggested that the degree of the collective motion in ionic conductors increases with the increase in Q/E-a.','suggested_association'),
('good ionic conductors','predicted to have','large Q/Ea','The model predicts that good ionic conductors will show large value of Q/E-a.','model_prediction')],scope='thermodynamics')
core(29,[
('H2/H2O low-oxygen-partial-pressure environment versus pureO2','increases conductivity and lowers','surface-exchange resistance in CGO','As expected, the results show increased conductivity and lower surface exchange resistance in H-2/H2O gas mixtures where the oxygen partial pressure is low compared to experiments in pure O-2.','observed_joint_outcome')],reason='方法能力介绍不另造材料因果，保留明确气氛条件下输运响应。',scope='measurement_method_model')
core(30,[
('initial and stationary temperature-voltage coefficients of symmetric thermogalvanic elements','used to determine','HCl Soret coefficients and thermal-transfer entropies at298.15K','The results obtained in measurements of the initial and stationary temperature voltage coefficients of symmetrical thermogalvanic elements with silver-chloride and quinhydron electrodes in the HCl-H2O-CH3CN system at 298.15 K were used to determine the Soret coefficients and standard entropies of thermal diffusion transfer of hydrogen chloride and the entropies of the H+ and Cl- ions moving in solution.','measurement_method')],scope='measurement_method_model')
core(31,[
('Na+ and K+ counterion synergy','enables','stable1.6m aqueous ferri/ferrocyanide thermocell','This study exploits the simple synergy between Na+ and K+ counter ions to achieve-to the best of our knowledge-the most concentrated stable aqueous ferricyanide/ferrocyanide thermocell to date, at 1.6 m [Fe(CN)(6)](3-/4-).','author_claim'),
('400% concentration increase over0.4m electrolyte','produces only166% increase in','electrical power','Despite increasing the concentration by 400% relative to the standard K-3/K-4[Fe(CN)(6)] electrolyte (0.4 m), electrical power production increased only 166%.','observed_nonproportional'),
('entering quasi-stable water-in-salt region up to2.4m','decreases','power','Pushing the system from conventional salt-in-water electrolytes into the quasi-stable water-in-salt region (up to 2.4 m) resulted in a decrease in power.','observed_condition')])
