from work import core
core(16,[
('3D multijunction BMWCNT solar-cell design','allows','electron-hole pair creation along x/y and z directions','It allows the creation of electron-hole pair not only from the top layer to bottom layer (z-axis direction) as the traditional 1D multijunction multiband but also in the x-axis (abscissa) and y-axis (ordinate) directions.','retracted_source_claim'),
('broad-spectrum harvesting including nanotube thermoelectric and thermo-ionic features','claimed to optimize','conversion efficiency','This optimized efficiency is achieved by harvesting visible light and all spectrums of the light including the utilization of thermoelectric and the thermo-ionic features exist in nanotubes.','retracted_source_claim')],reason='题名明确RETRACTED；保留原文主张用于覆盖审计，但不可作为主机制图有效支持证据。',scope='retracted_excluded')
core(17,[
('tortuous electrode ionic pathways and concentration gradient','reduce reaction rate and limit','TEC output current','However, the highly tortuous ionic pathways of the electrodes limit the output current from the TECs by reducing the reaction rate inhibited by a concentration gradient in the electrode.','author_claim'),
('sequential stacking of highly aligned DWCNT sheets','facilitates','efficient ion transport','In this work, we investigate an electrode structure that facilitates efficient ion transport by sequentially stacking highly aligned double-walled carbon nanotube (DWCNT) sheets.','author_claim'),
('increasing parallel DWCNT stacks from one to three','increases at DeltaT22C','output power density','As the number of stacks increases from 1 to 3 layers oriented in parallel, the output power increases from 113 to 187 mW/m(2) at a small temperature difference of 22 degrees C.','observed'),
('orthogonal lamination of three DWCNT layers','further improves','output power density','The output power with 3-layer DWCNT sheets can be further improved to 200 mW/m(2) by implementing an orthogonal lamination.','observed')],scope='device_engineering')
core(18,[],reason='说明研究了沉积电位和表面活性剂对形貌/PEC的影响，但未报告影响方向或具体发现；效率孤立数值不能补造机制关系。',scope='other_adjacent_domain')
core(19,[
('increasing S content with smaller S2- than Se2-','decreases','lattice parameters a and c','As the S content (y) increased, the lattice parameters a and c decreased, attributed to the smaller ionic radius of S2- compared to Se2-, as X-ray diffraction analysis identified single-phase regions for 0 <= y <= 0.4 and 1.6 <= y <= 2, respectively.','author_attribution'),
('intermediate S composition 0.8 to 1.2','produces','eskebornite/chalcopyrite composite rather than complete solid solution','However, for 0.8 <= y <= 1.2, a composite phase of eskebornite and chalcopyrite formed, indicating incomplete solid solution behavior in the intermediate range.','observed'),
('increasing S content/end-member semiconductor combination','increases conductivity and changes','Seebeck polarity from p to n','Thermoelectric measurements showed a sharp increase in electrical conductivity with increasing S content, alongside a transition in the Seebeck coefficient from positive (p-type) to negative (n-type), attributed to the intrinsic semiconducting nature of the end-member compounds.','observed_joint_outcome'),
('inverse electrical conductivity-Seebeck relationship','prevents significant improvement in','power factor','Despite these changes, the power factor did not show significant improvement due to the inverse relationship between electrical conductivity and the Seebeck coefficient.','null_effect_attribution'),
('lattice imperfections and mass fluctuation under solid-solution formation','enhance scattering and reduce','thermal conductivity','The thermal conductivity decreased significantly with solid solution formation, with CuFeSe0.4S1.6 exhibiting the lowest value of 0.97 Wm-1K-1 at 623 K, a result of enhanced phonon scattering at lattice imperfections and the mass fluctuation effect.','joint_author_claim'),
('thermal-conductivity reduction with modest power factor','does not substantially enhance','ZT','However, the reduction in thermal conductivity was insufficient to compensate for the modest power factor, resulting in no substantial enhancement in the thermoelectric figure of merit.','negated')])
core(20,[
('moderate interlayer swelling in weathered biotite','dramatically lowers','interlayer ion-migration barriers','We find that, at equilibrium interlayer spacing, barriers are large. But they dramatically drop under moderate interlayer swelling.','computational_prediction'),
('reduced migration barriers including K about 0.4eV','indicate feasibility of','ionic conduction in weathered biotite','In particular, the barriers for K reach similar to 0.4 eV. These results indicate the feasibility of ionic conduction in WB.','computational_inference')])
core(21,[
('increasing hydrostatic pressure on RbSnCl3/RbSnBr3','decreases','band gap','The studied perovskites are direct band gap semiconductors at ambient pressure, and the band gap decreases with increasing induced pressure.','computational_prediction'),
('pressure','improves','optical absorbance and conductivity','In addition to the band gap variations with pressure, the optical absorbance and conductivity of the perovskites are also improved, making them more appropriate for optoelectronic applications.','computational_prediction'),
('higher pressure','shortens bonds and strengthens','Rb-Cl/Br and Sn-Cl/Br bonding','Besides, the bond length of Rb-Cl/Br and Sn-Cl/Br steadily decreases, and both compounds exhibit stronger bonding at high pressure.','computational_prediction'),
('pressure','enhances','anisotropic behavior','Similarly, the anisotropic behavior of the perovskites is also enhanced due to the pressure effect.','computational_prediction')],reason='摘要主体为光电/力学性质，无直接热电机制测试；保留相邻材料机制但不冒充iTE机制证据。',scope='other_adjacent_domain')
core(22,[
('larger Nb5+ radius and oxygen-sublattice relaxation','increase volume and compressibility','Nb-substituted CaSiO3','while reducing the bulk modulus, consistent with enhanced compressibility driven by the larger Nb5+ ionic radius and associated oxygensublattice relaxation.','computational_joint'),
('Nb4d/O2p donor states introduced by Nb','narrow at12.5% and close at25%','CaSiO3 electronic band gap','Nb introduces Nb-4d/O-2p donor states that narrow the gap at 12.5% doping and eventually close it at 25% Nb, yielding a metallic 4d conduction manifold at the Fermi level.','computational_prediction'),
('25% Nb carrier reorganization','yields negative Seebeck and low-temperature PF peak','higher thermoelectric ZT','At 25% Nb, a/t and x rise sharply with temperature, the Seebeck coefficient becomes negative, and a pronounced low-temperature power-factor peak emerges, producing a ZT maximum approximately an order of magnitude larger than that of the other compositions.','computational_joint_outcome')],reason='聚焦结构—电子—热电主链，磁性/压电旁支不计入热电核心分母；可疑数值和单位保留原样，不擅自校正。')
core(23,[
('amphiphilic DBS- micellization on agarose chains','forms','unique porous structure','A unique porous structure is formed due to the micellization of the amphiphilic DBS- with the hydrophilic benzenesulfonic group attached to the hydrous agarose gel chains, while the hydrophobic alkyl chain point to the pore centers.','author_claim'),
('DBS- micelles','are almost immobile compared with','Na+','As a result, the DBS- micelles are almost immobile as compared with Na+, which can be reconsidered as a part of the gel matrix.','observed_comparison'),
('decoupled Na+/DBS- thermodiffusion','accounts for','high positive thermopower','The exclusively high thermopower is relative to the successfully decoupling the thermodiffusion of cation Na+ and anion DBS-.','author_attribution')])
