from work import core
core(40,[('sodium pyrrolidone carboxylate addition','enhances','TGIH water retention and mechanical properties','Subsequently, the water retention and mechanical properties of TGIH were enhanced by introducing the natural moisturizing factor sodium pyrrolidone carboxylate.','joint_outcome')])
core(41,[('temperature-responsive thermogalvanic gel','enables','self-powered body-temperature patch','Given the excellent temperature response of the thermogalvanic gel, we have fabricated a self-powered body temperature monitoring patch that could be conformally attached on the wrist or other points.','reported_function'),('strain responsivity of gel patch','enables','wrist pulse recognition','Meanwhile, the gel patch possesses high responsivity on strain that can recognize the pulse beat at the wrist.','reported_function')],scope='application_sensing')
core(42,[('fully additive printed thermogalvanic module fabrication','enables','precise complex assembly without stacking or wiring','This fully additive and scalable fabrication strategy enables the precise assembly of complex architectures without traditional stacking or wiring.','author_claim')],scope='device_engineering')
core(43,[('DFT-derived ion-solvent interaction features','strongly correlate with','Seebeck coefficient','Our approach parametrizes the Seebeck coefficient by leveraging the strong correlation between DFT-derived ion-solvent interaction features and limited experimental data.','association'),('polarity-related features','identified by SHAP as dominant factors in','ML solvent screening','A hybrid ML framework combining high-throughput DFT and interval regression was developed to screen extensive solvent candidates with SHAP analysis identifying polarity-related features as dominant factors.','model_association_not_causal')],scope='measurement_method_model')
core(44,[('thermoelectric conversion and gel piezoresistance','jointly enable','self-powered temperature and strain sensing','By leveraging the thermoelectric conversion in conjunction with the inherent piezoresistive effect of a gel electrolyte, self-powered sensing is achieved by utilizing the temperature difference between the human body and the external environment.','joint_mechanism'),('zwitterion incorporation','enhances','hydrogel dehydration and low-temperature resistance','The incorporation of zwitterions further augments the resistance of the hydrogel to dehydration and low temperatures, allowing maintenance of more than 90% of its weight after 48 h in the air.','joint_outcome')],scope='application_sensing')
core(45,[],reason='描述腐蚀模拟及理论实验吻合，未陈述具体条件到腐蚀效应或机理关系。',scope='corrosion_electrodeposition')
core(46,[('molybdenum nitride quantum dots in carbon matrix','activate','thermoelectrical behavior','Here, a facile strategy is demonstrated to fully activate the thermoelectrical behavior through simulation-guided electrode engineering, which is realized by incorporating battery-type molybdenum nitride quantum dot into carbon matrix.','author_claim'),('3D skeleton, abundant electroactive sites and high conductivity','jointly enable','large thermopower, power density and durability','Benefitting to the well-developed 3D skeleton, abundant electroactive sites, and high conductivity, as-constructed device can achieve a giant thermopower of 53.6 mV K-1, normalized power density of 6.83 mW m-2 K-2, and good durability, which can meet the power demands of wearable sensors and small electronic devices.','joint_attribution')],scope='device_engineering')
core(47,[('temperature-driven electrode reactions across ion-exchange membrane','increase','redox-species concentration differences','When the two electrodes were connected, [Fe(CN)6]4- was reduced to [Fe(CN)6]3- at the high-temperature electrode and the opposite reaction took place at the low-temperature electrode. This increases the [Fe(CN)6]3- and [Fe(CN)6]4- concentration differences between the two region separated by the ion-exchange membrane, and these differences could supply electric power after the temperature difference between the electrodes was removed.','author_claim_redox_label_inconsistent'),('stored redox concentration differences','supply','electrical power after removal of temperature difference','This increases the [Fe(CN)6]3- and [Fe(CN)6]4- concentration differences between the two region separated by the ion-exchange membrane, and these differences could supply electric power after the temperature difference between the electrodes was removed.','author_claim')],reason='原摘要将[Fe(CN)6]4−到3−称reduced，与氧化态方向矛盾；不把该具体半反应作为已核实机制。',scope='device_engineering')
