from work import core
core(8,[
('temperature above 410 K','transforms','Ag8GeSe6 orthorhombic structure toward face-centered cubic with intervening phase separation','the crystal structure of Ag8GeSe6 evolved from orthorhombic at room temperature to face center cubic above 410 K, with a region of phase separations in between','observed'),
('phonon mean free path near interatomic spacing','accounts for','ultralow thermal conductivity','Ag8GeSe6 exhibited ultralow thermal conductivities over a wide temperature range as the phonon mean free path was down to the order of interatomic spacing','author_claim'),
('Se deficiency variation','optimizes','carrier concentration and power factor','varying Se deficiency effectively optimized the carrier concentration and power factor','author_claim')])
core(9,[
('high-degeneracy weak-dispersion valley','produces','large Seebeck magnitude but low electrical conductivity','The valley with a high band degeneracy consists of the bands with a weak band dispersion, leading to large magnitudes of the Seebeck coefficient but low electrical conductivity.','computational_joint_outcome'),
('low-degeneracy strongly dispersive valley','produces','high electrical conductivity but small Seebeck magnitude','The valley with a low band degeneracy is made up of the bands with an intense band dispersion, resulting in a high electrical conductivity but small magnitudes of the Seebeck coefficient.','computational_joint_outcome'),
('ionic radius of Ln','linearly increases','valley energy difference DeltaE in LnZnSbO','The Delta E value of LnZnSbO linearly increases with the ionic radius of Ln.','computational_association'),
('moderate valley energy difference in Ce-Nd LnZnSbO','favors','thermoelectric performance','As a result, LnZnSbO (Ln = Ce-Nd) with the moderate values of Delta E shows a better thermoelectric performance.','computational_prediction')])
core(10,[
('oxygen partial pressure','controls with exponents -1/4 and +1/4','n-type and p-type conductivities respectively','Both n- and p-type conductivities are found with the dependence of - 1/4 and 1/4 powers of po(2), respectively, and no indication of an ionic conductivity is observed.','observed_association'),
('measured ZrTiO4 transport','shows no indication of','ionic conductivity','no indication of an ionic conductivity is observed.','negated'),
('lower-valent impurities or dopants','determine in proposed defect model','oxygen vacancy concentration','A defect model has been proposed wherein an extrinsic oxygen vacancy formation is predominant, in which the concentration of oxygen vacancy is determined by the amount of lower-valent impurities or dopants, and excellent agreement is found between experimental and calculated results.','proposed_model'),
('partial electron conductivity','correlates strongly with','anomalous c-axis expansion','The partial conductivity of electrons showed a strong correlation with the anomalous expansion of the c-axis.','association')])
core(11,[
('drying and regeneration','allows recovery and slightly higher','ionic Seebeck coefficient','After drying and regeneration, ITEG-re could even exhibit a higher ionic Seebeck coefficient of 11.8 mV K-1.','observed_comparison')],reason='只纳入明确处理—响应关系；单独性能数值、LED展示与耐环境属性清单不扩写微观机制。',scope='device_engineering')
core(12,[
('partial Ce/Nd filling together with Co substitution at Fe sites','suppresses','FeSb2 marcasite formation','The formation of a marcasite phase (FeSb2) was significantly suppressed by partially filling the voids with Ce/Nd and making a Co substitution at the Fe site.','joint_author_claim'),
('Co charge compensation and Nd filler content','increases','Seebeck coefficient','The Seebeck coefficient increased with the charge compensation of Co and filler content of Nd; however, the electrical conductivity decreased.','joint_author_claim'),
('Co charge compensation and Nd filler content','decreases','electrical conductivity','The Seebeck coefficient increased with the charge compensation of Co and filler content of Nd; however, the electrical conductivity decreased.','joint_author_claim'),
('higher carrier concentration under partial versus complete double filling','causes','higher electrical conductivity and lower Seebeck coefficient','The partially double-filled specimens had a higher electrical conductivity and lower Seebeck coefficient than the completely double-filled specimens, due to the increase in carrier concentration.','joint_outcome'),
('comparable Ce/Nd atomic masses and ionic radii','explain lack of significant reduction in','lattice thermal conductivity with partial double filling','The lattice thermal conductivity was expected to decrease via partial double filling with Ce and Nd; however, it did not change significantly because of the comparable atomic masses and ionic radii of Ce and Nd.','null_effect_attribution'),
('increasing Co content','lowers','intrinsic conduction onset temperature and thereby changes ZT','Co substitution had an influence on the ZT values due to the change in the intrinsic conduction onset temperature, which decreased with increasing Co content.','author_claim')])
core(13,[
('Cr addition in Ca3Co4-xCrxO9+delta','increases','resistivity and Seebeck coefficient','The resistivity and the Seebeck coefficient increased while the thermal conductivity was suppressed when Cr was added into the system.','observed_joint_outcome'),
('Cr addition in Ca3Co4-xCrxO9+delta','suppresses','thermal conductivity','The resistivity and the Seebeck coefficient increased while the thermal conductivity was suppressed when Cr was added into the system.','observed'),
('Co/Cr charge-state and ionic-radius differences','discussed as explanation for','changed thermoelectric properties','Explanation of the change in thermoelectric properties was discussed regarding the difference in the charge states and the ionic radii between Co and Cr ions.','discussed_explanation')])
core(14,[
('spin-orbit coupling','has negligible effect on','PdSe monolayer electronic properties','The spin-orbit coupling is found to play a negligible effect on the electronic properties of PdSe monolayer.','computational_null'),
('anisotropic phonon group velocity and intrinsic structural anisotropy','jointly cause','anisotropic lattice thermal conductivity','The lattice thermal conductivity of PdSe monolayer exhibits remarkable anisotropic characteristic due to anisotropic phonon group velocity along different directions and its intrinsic structure anisotropy.','computational_joint'),
('compromised mobility despite low thermal conduction','limits','ZT to moderate values','The compromised electronic mobility despite a relatively low thermal conduction results in a moderate ZT value but significantly anisotropic thermoelectric performance in single-layer PdSe.','computational_prediction')])
core(15,[],reason='综述摘要仅列结构、性能领域和制备综述范围，未给足够具体的主体—关系—客体机制陈述。',scope='review_overview')
