from match import match
M=('missing',[],'未抽出该关系；引用中出现不等于已形成关系。')
match(0,[('exact',[1],'主体、产生关系及原子Seebeck结果一致。'),M,M])
match(1,[M,('exact',[1,2],'两条边合起来覆盖输运热与电压；原谓词保留cellulose介导。'),M])
match(2,[M,('partial',[1],'ZT提高已提取，但关系未标出计算预测模态。')])
match(3,[M,('partial',[1,2],'两条边明确joint origin且hypothesis，但未绑定共同因素组，不能当独立原因。')])
match(4,[('partial',[1],'遗漏共同因素Born有效电荷。'),M,M,M])
match(5,[M,('exact',[1,2,3],'三条边共同覆盖二价/一价比较、熵/扩散与热电势，条件在统一证据中。'),M])
match(6,[M,M])
match(7,[M,('exact',[1],'ILM激活抑制晶格热导。'),M,M])
match(8,[M,M,('partial',[1],'只提取载流子浓度优化，未提取功率因子优化。')])
match(9,[('exact',[1,2],'高简并弱色散谷条件在谓词与共享证据中，S增大与电导低两条完整。'),M,M,M])
match(10,[M,('exact',[1],'no indication及negated明确，并非证明绝无离子传导。'),M,M])
match(11,[M])
match(12,[M,M,M,M,('partial',[1],'未显著改变热导及质量半径原因保留，但因果主语改为partial filling，严格参考关系仅部分覆盖。'),M])
match(13,[('partial',[1],'只提取Seebeck增加，缺少电阻率增加。'),M,M])
match(14,[M,('partial',[1],'谓词保留结构各向异性共同因素，但未绑定联合因素组。'),M])
