from match import match
M=('missing',[],'未形成该核心关系。')
match(45,[])
match(46,[('partial',[1],'只抽到电活性位点，未建立电热行为活化的参考关系。'),('partial',[2,3],'联合主语缺3D骨架绑定，结果只覆盖thermopower。')])
match(47,[M,('exact',[1],'温差撤去后以浓度差供电，未抽取矛盾半反应。')])
match(48,[('partial',[1],'只抽到溶剂限制氢键，未提取抗冻耐干结果。'),M])
match(49,[M])
match(50,[('exact',[1],'explicit magnitude避免负Seebeck增减歧义。')])
match(51,[M,M,('exact',[1],'否定依赖关系以反向does not determine等义保留，dual-cell model限定。')])
match(52,[('partial',[1],'TGC生成电场已提取，但未建立温差驱动关系。'),('exact',[2],'电场促进伤口愈合，作为作者研究结论。')])
match(53,[('partial',[1,2],'两因素jointly明确但没有联合绑定组。'),M,M])
match(54,[('partial',[1,2],'两联合因素没有绑定组。'),('exact',[3],'联合氧化/还原主语与Fe3耗尽终点保留。'),M])
match(55,[])
match(56,[M,('exact',[1,2],'同一浓度条件下增强redox/抑制热扩散的相反方向均保留。'),M])
match(57,[('partial',[1,2],'两因素jointly明确但没有联合绑定组。')])
match(58,[('exact',[1,2],'两条边完整覆盖溶剂化差异与对流抑制。'),('partial',[3,4],'原文联合双结果被分配成两个独立因果，严格联合表述未保留。'),M])
match(59,[('exact',[1],'两梯度联合结果明确。'),('exact',[2],'协同离子输运、TGC/RED耦合和功率增强明确，设计条件保留于证据。')])
