from match import match
M=('missing',[],'未形成该核心关系。')
match(15,[])
match(16,[('partial',[1],'设计可能性保留，但原关系无撤稿来源限制。'),M])
match(17,[M,('exact',[1],'堆叠取向电极设计与高效离子输运对应。'),M,M])
match(18,[])
match(19,[M,M,M,M,('exact',[1],'联合因素在同一主语中，增强散射与热导减少明确。'),M])
match(20,[('exact',[1],'适度层间膨胀降低势垒，谓词明确in computation。'),M])
match(21,[('partial',[1],'方向正确，未保留计算模态及具体材料范围。'),M,M,M])
match(22,[M,('partial',[1,2],'Nb引入态及25%闭隙可见，未提取12.5%窄隙。'),M])
match(23,[('exact',[1],'胶束形成多孔结构明确。'),('exact',[2],'比较不动性完整编码在宾语中。'),M])
match(24,[M])
match(25,[M,('exact',[1,2],'两边覆盖阻燃和氧指数，引用明确包覆木材对象。'),M])
match(26,[M,M,('exact',[1],'界面静电环境修改提升PF，保留作者归因。')])
match(27,[M,('partial',[1],'保留jointly，但只覆盖力学表现，遗漏热导与储能模量。')])
match(28,[M,('exact',[1],'Q/Ea增加与集体运动关系且hypothesis保留。'),M])
match(29,[('exact',[1,2],'气氛对照及两项输运结果完整；association没有误升因果。')])
