from pairs import pair
D='reject';U='uncertain'
pair(35,D,'温度依赖迁移率驱动扩散是机制，双电层界面不对称是结构状态，不能等价。')
pair(36,D,'异温充放电操作与redox功能基团不同。')
pair(37,D,'极性冠层结构与保持对离子可移动的状态不同。')
pair(38,D,'alpha-CD主客体配位不等于P0931已定义的电化学Seebeck系数alpha。')
pair(39,D,'离子偶极相互作用与IL富集球形结构不同。')
pair(40,D,'低结晶状态与剥离能物理量不同。')
pair(41,D,'带自然通道胶原纤维材料不等于含氧官能团组分。')
pair(42,D,'离子ZT性能指标与CPE侧基极性描述符不同。')
pair(43,D,'凝胶阴离子扩散与Ta/吸附物交换扩散，物种和过程边界不同。')
pair(44,D,'可生成可动阴离子的掺杂物与电解物种分离过程不同。')
pair(45,D,'对离子凝聚过程与PS20-2@PE4/6样品材料不同。')
pair(46,D,'选择溶剂化相互作用与压电内场不同。')
pair(47,D,'赝电容储荷过程与添加离子实体不同。')
pair(48,D,'赝电容储荷过程与载流子实体不同。')
pair(49,D,'离子Peltier过程与低有效质量量性状态不同。')
pair(50,U,'泛称ionic hydrogel与特定稀释NC凝胶缺少共同配方或定义；同属凝胶不足以同义。')
pair(51,D,'性能泛称与另一体系outstanding性能还带程度限定且载流范围不同，不能严格等价。')
pair(52,D,'金属阳离子/空穴协作过程与pristine SrTiO3材料状态不同。')
pair(53,D,'P0644全文确认high conductivity为离子电导，明确不同于热导。')
pair(54,D,'有序结构增加与掺杂含量增加是不同材料变化。')
pair(55,D,'P0607全文为金属离子介导交联，不能与Cl阴离子相同。')
pair(56,D,'P0891指Ag8SiTe6阳离子低温冻结行为，与Cl阴离子物种不同。')
pair(57,D,'CPG-L2全文为Ca-alginate/PAAm/glycerol/LiBr，另一为WPU/ChCl:EG，不同配方。')
pair(58,U,'CNF/DES凝胶与栅控高电容离子胶未给共同组成，不能以gel简称合并。')
pair(59,D,'结构设计策略与thermopower性能指标不同。')
pair(60,D,'原位配体衍生有机无机界面不是Lewis酸性离子液体介质。')
pair(61,D,'微结构与1wt%离子液体添加量不同。')
pair(62,D,'CMHC全文解析为羧甲基半纤维素材料，非microstructure。')
pair(63,D,'V全文是钒元素，非热电Seebeck效应。')
pair(64,D,'p-n转换过程与相变熵量不同，不能因均出现transition合并。')
pair(65,D,'increment回指离子热电势增量，与离子加合物及中性掺杂物材料不同。')
pair(66,D,'键软化过程与易剪切晶面结构不同。')
pair(67,D,'离子-聚合物作用不等于SWCNT网络植入/AuCl掺杂/后处理策略。')
pair(68,U,'Se掺杂按元素指定，n掺杂按载流类型指定；此摘要未建立两者同一掺杂行为范围。')
pair(69,D,'稀土离子半径是量，稀土向Sb电荷转移为过程。')
