from roles import role
role(80,'p','无序对输运的影响作为被抑制的效应机制。')
role(81,'s','结构与热性质近各向同性是联合状态特征，不是性能数值。','compound_state')
role(82,'q','散射强度与弛豫时间为联合输运量性表述，过程/量混合须保留。','compound_mixed_process_quantity')
role(83,'q','与应变/弯曲稳定并列的reduced modules疑似modulus，但原拼写未确认，仅定量性对象。','source_typo_unresolved')
role(84,'s','organic liquid thermoelectric转换器件，与水系器件作对照。','device_structure')
role(85,'p','层间作用减弱和声子限域联合机制，保留复合性。','compound_interaction_process')
role(86,'q','计算输运系数双量在温度变化下近恒定，此处不是提升性能目标。','compound_quantity')
role(87,'i','阳离子配位和阴离子Hofmeister对聚合物的复合作用。','compound_interaction')
role(88,'s','PCM容器与商用TEG组合器件结构。','compound_device_structure')
role(89,'q','Seebeck与电阻率变化是被解释的双输运量，保留两者同时性。','compound_quantity')
role(90,'s','针网型离子风冷却器件，不是离子风过程本身。','device_structure')
role(91,'s','两材料声子态间声学失配是界面状态特征。')
role(92,'p','低群速度与强三声子散射的联合降热导机制，量与过程混合。','compound_quantity_process')
role(93,'s','极端非谐与弱键作为势能面联合特征。','compound_state')
role(94,'s','非谐性与动态无序为共同结构特征。','compound_state')
role(95,'e','链呼吸模型作为解释超常电导的假设表征；不可直接当已证实链运动。','ontology_fit_limited_hypothesis_model')
role(96,'s','回指电导最小、抗磁增强和热电势反号的复合异常状态，非未知材料。','resolved_anaphor_compound_state')
role(97,'d','施加PBE-D3修正属于计算方案操作；非材料改性。','computational_method_design')
role(98,'e','动量转移论证是模型解释表征；不同于实际测得动量转移过程。','model_argument')
role(99,'s','高原子密度与强结构无序的联合材料状态。','compound_state')
role(100,'f','迁移率增强带来的S/电导双目标表现，复合节点保持。','compound_performance_quantity')
role(101,'s','有序导电域与迁移率的复合输运状态，不拆出独立原因。','compound_state_quantity')
role(102,'p','热扩散测量是实验过程，不是热扩散系数。','measurement_process')
role(103,'f','高电导低S的联合热电性能结果，不能丢失方向。','compound_performance_quantity')
role(104,'s','局部畸变、弱键、强非谐的复合微结构状态。','compound_state')
role(105,'s','FeCl3或水gate指装置结构/门控组分，不当作电压工况。','device_structure')
role(106,'q','水凝胶电学/热力学/热电/力学多性质概括，仍未具体化。','compound_underspecified_quantity')
role(107,'s','非谐与无序是共同原子动态状态。','compound_state')
role(108,'i','广泛氢键与电荷稳定的联合相互作用，非单一氢键。','compound_interaction')
role(109,'i','掺杂引起的短程扰动抵消长程库仑场，作为电子-掺杂作用。')
role(110,'q','conduction band activity为未定义的量性活性描述，不改成电导率。','underspecified_quantity')
role(111,'s','氧化程度与纳米结构组成联合材料状态。','compound_state')
role(112,'q','三种电荷/质量输运性质并列，为复合量节点。','compound_quantity')
role(113,'s','软共价键与离子层共存的复合结构。','compound_state')
role(114,'p','BF4致混乱效应属于作用过程，不能等同BF4本体。')
role(115,'s','孤对电子、弱相互作用及离子键共同构成电子/键合状态。','compound_state_interaction')
role(116,'p','电化学Seebeck效应是响应机制，不等同其温度系数。')
role(117,'s','对称加热微接触装置是测试器件结构。','measurement_device_structure')
role(118,'p','铜运动与无序化联合驱动相变，动态过程为主并含迁移能力。','compound_quantity_process')
role(119,'p','AC实验为测量验证过程，不是交流频率条件。','measurement_process')
