from roles import role
role(40,'p','电极依赖效应作为输运贡献机制，未明确具体相互作用。','underspecified_process')
role(41,'s','低压有机晶体管为受栅控的完整器件。','device_structure')
role(42,'s','模块加窄带滤光器的组合传感单元。','compound_device_structure')
role(43,'p','离子凝胶/CPNF界面电容效应是储荷/极化响应机制，不是给定电容数值。')
role(44,'q','CPNF电学性质未指定量，不能替换成电导或电阻。','underspecified_quantity')
role(45,'s','掺杂水平与形貌的复合材料状态，保留混合属性。','compound_state')
role(46,'s','能量无序为电子态分布的无序状态，并非热力学熵。')
role(47,'q','双电层强度为量性描述，定义不明确，不改为电势或电场强度。','underspecified_quantity')
role(48,'q','载流子输运特征是未具体化的一组量性性质。','underspecified_quantity')
role(49,'s','离子传导单向取向是各向结构/输运状态，非普通电导数值。')
role(50,'s','基于金电极表面组装的纸芯片整体器件。','device_structure')
role(51,'e','SPH理论模型用于解释数据；作为模型表征保留，注明本体缺少独立model类别。','ontology_fit_limited_model_representation')
role(52,'f','高温区热电势为研究目标性能；不将热电power误当瓦特功率。')
role(53,'p','K-means作为滤噪信号处理过程，非材料实体或物理机制。','computational_analysis_process')
role(54,'p','电荷水洼效应影响输运的物理机制。')
role(55,'q','低温输运性质泛称，不能细化为电导率。','underspecified_quantity')
role(56,'f','SWCNT thermoelectric power为增强目标，定义不充分时不强制并为Seebeck。','underspecified_performance')
role(57,'d','叶脱水处理与电极选择是两项共同设计操作。','compound_design')
role(58,'i','流体动力摩擦是近表面黏滞阻力相互作用，不是特定摩擦系数。')
role(59,'s','结构复杂、键强差异与非谐性组成联合材料状态，不拆成独立因果。','compound_state')
role(60,'p','Seebeck效应是热电响应机制；效应增强不等于明确系数变化。')
role(61,'e','离子影响氢键能力充当解释热电性能的特征描述符，未定义具体力学量。','underspecified_descriptor')
role(62,'m','疏水聚合网络与离子液体作为复合材料组分。','compound_material')
role(63,'s','ITEG整体发电器件，而非材料配方。','device_structure')
role(64,'f','充放电比为目标性能，但原句不说明容量/时间/电荷哪个比值。','underspecified_performance')
role(65,'s','热电转换系统为整体器件结构。','device_structure')
role(66,'f','电子热电势是实验及模型比较的目标量。')
role(67,'q','离子液体动力学作为成束机理参数泛称，不强指定速率。','underspecified_quantity')
role(68,'p','混合碱效应是输运机制现象，不等同混合碱添加操作。')
role(69,'p','ionic origin给出机制类别，未指定Soret或redox。','underspecified_process')
role(70,'f','S与a同时增强是联合热电性能状态，保留符号及同时性。','compound_performance')
role(71,'f','can function as generator表述发电功能，不是额外独立器件实体。','device_function')
role(72,'s','分段组合形成的高效发电器件对象，保留性能修饰。','device_structure')
role(73,'e','输运热与活化能的关系属于模型解释量间关系表征，不是新基本物理量。','model_relation_descriptor')
role(74,'f','可靠估计电子热导是方法功能目标，而非电子热导本身。','measurement_function')
role(75,'s','小晶粒与纳米相联合微结构。','compound_state')
role(76,'s','与PV集成的iTEG器件层。','device_structure')
role(77,'p','TEP测量是测量过程，非热电势值。','measurement_process')
role(78,'e','填充分数、价态、半径共同为Oftedal图预测描述符。','compound_descriptor')
role(79,'e','Oftedal图用于呈现结构关系，保留模型/结构表征角色。','model_representation')
