from roles import role
role(0,'q','比较阴阳离子热泳差异的量性表达；具体输运量未定义，不能等同扩散系数差。','underspecified_quantity')
role(1,'f','反应效率作为改善目标，而非反应过程本身。','underspecified_performance')
role(2,'i','冠醚complexation指配位相互作用；不补造结合离子。','unspecified_partner')
role(3,'q','阴阳离子扩散差异是比较量，原文未明确是系数还是位移差。','underspecified_quantity')
role(4,'p','减少热扩散离子体积是机制变化过程；不当成定义清晰的体积数值。','underspecified_process')
role(5,'i','微结构与溶液界面作用；不细化成未知静电或配位作用。','underspecified_interaction')
role(6,'s','氧化/还原物种水合壳行为差异，结构行为状态概括；不是直接定义的熵。','underspecified_state')
role(7,'q','increase kinetics为动力学快慢量性概括，不能私自当特定速率常数。','underspecified_quantity')
role(8,'s','配位水的径向分布为溶剂化结构分布，不等同单个半径量。')
role(9,'q','界面电阻势垒作为受形变调制的量；不混成电子活化能。','underspecified_quantity')
role(10,'s','DES共晶性质所指混合物共晶状态，不补成具体熔点值。','underspecified_state')
role(11,'q','厚度/层数控制量的复合短语；保留两量，不合并到普通厚度。','compound_quantity')
role(12,'s','TGC敷料为整体器件结构，非伤口愈合应用本身。','device_structure')
role(13,'p','chaotropic效应作为扰乱结构的机制效应；未写具体熵值。')
role(14,'p','应变下压阻响应参与转导机制，非特定电阻率数值。')
role(15,'f','overall thermoelectric power在此为输出性能；未给明是S或P，保持泛称。','underspecified_performance')
role(16,'p','提取手指温度特征是测量/识别操作过程，非温度状态本身。','measurement_process')
role(17,'s','被使用的完整热电化学器件。','device_structure')
role(18,'s','具有应变响应的整体凝胶贴片器件。','device_structure')
role(19,'q','扩散差异是未定义具体比较方式的量类。','underspecified_quantity')
role(20,'p','离子热电效应作为过程性机制整体，不能等同某单一Seebeck量。')
role(21,'p','阳离子运动自增强指输运过程，含义宽泛但过程角色可定。','underspecified_process')
role(22,'q','thermal mobility为热驱动迁移能力量；不直接等同电迁移率。','underspecified_quantity')
role(23,'i','LiCl与水的水合作用被用来解释抗冻吸湿；不细化配位结构。','underspecified_interaction')
role(24,'q','孔隙率与连通程度是结构参数复合量，保留复合边界。','compound_quantity')
role(25,'p','浓度梯度附加效应是驱动机制，不等同单纯浓度梯度物理量。')
role(26,'q','电极动力学作为与系数平衡的速率能力，未定义具体常数。','underspecified_quantity')
role(27,'p','改变溶剂化的过程，非具体水合壳状态。')
role(28,'q','热力学与动力学性质为多量综合，未定义具体两个指标。','compound_underspecified_quantity')
role(29,'p','测量热电化学曲线为测量过程，不是曲线本身。','measurement_process')
role(30,'d','扫描测量方法和三电极装配的复合测试设计；原ISV拼写保留。','compound_measurement_design')
role(31,'p','阻抗分析是提取参数的分析过程。','measurement_process')
role(32,'s','讨论可行性的M-H完整电池器件结构。','device_structure')
role(33,'q','腐蚀强度可由电流/质量损失反映，但不强行指定唯一指标。','underspecified_quantity')
role(34,'s','多层薄膜集成电池，整体器件结构。','device_structure')
role(35,'s','溶剂自由度与有序程度复合构型状态；不合并为单一熵量。','compound_state')
role(36,'s','含两种电极的非对称电池结构。','device_structure')
role(37,'s','spin mixing的非对称性是输运状态特征，不是spin mixing过程本身。')
role(38,'p','孔溶液离子产生的热电效应机制。')
role(39,'d','二次掺杂/去掺杂/离子能量筛选作为组合调控策略，保持复合操作。','compound_design')
