from author import *
paper('P0482','mixed')
r('PEDOT doping-level modifications','q','directly correlate with','Seebeck coefficient enhancement','q','Doping level modifications of PEDOT are characterized using UV-Vis spectroscopy and directly correlate with the observed Seebeck coefficient enhancement.',cond='PEDOT:PSS films post-treated with EMIM DCA, AMIM DCA or EMIM TCB',assertion='association',mod='experimental')
q='Grazing incidence small-angle X-ray scattering (GISAXS) demonstrates the morphological rearrangement towards an optimized PEDOT domain distribution upon IL post-treatment, directly facilitating the interconductivity and causing an increased film conductivity.'
r('IL post-treatment','d','rearranges morphology toward','optimized PEDOT domain distribution','s',q,mod='experimental')
r('optimized PEDOT domain distribution','s','directly facilitates','interconductivity','f',q,cond='IL post-treated PEDOT:PSS thin films',mod='experimental')
r('optimized PEDOT domain distribution','s','increases','film conductivity','q',q,cond='IL post-treated PEDOT:PSS thin films',mod='experimental')
r('improvements in Seebeck coefficient and conductivity','q','increase','power factor up to 236 mu W m(-1)K(-)(2)','q','Based on these improvements in Seebeck coefficient and conductivity, the power factor is increased up to 236 mu W m(-1)K(-)(2).',joint=['improved Seebeck coefficient','improved conductivity'],mod='experimental')
r('small sterically unhindered IL ions with strong localized charge','x','appear beneficial for boosting','thermoelectric performance','f','Subsequently, a model is developed indicating that ILs, which contain small, sterically unhindered ions with a strong localized charge, appear beneficial to boost the thermoelectric performance of post-treated PEDOT:PSS films.',cond='IL post-treated PEDOT:PSS films',assertion='hypothesis',mod='theoretical')
paper('P1176','unspecified',note='high-symmetry.-phase notation malformed; no phase symbol inferred.')
r('alloying Cu7PSe6 with Cu7PS6','d','provides','continuous solid solution','s','Alloying of Cu7PSe6 with Cu7PS6 provides a continuous solid solution over the whole compositional range, as shown in the proposed phase diagram for the Cu7PS6-Cu7PSe6 system.','thermo','whole compositional range')
r('Cu7P(SxSe1-x)6 solid solutions','m','possess','dramatically low lattice thermal conductivity','q','As a member of liquid-like materials, the investigated Cu7P(SxSe1-x)(6) solid solutions possess a dramatically low lattice thermal conductivity, as low as similar to 0.2-0.3 W m(-1) K-1, over the entire temperature range.',cond='entire investigated temperature range; ~0.2-0.3 W m(-1) K-1')
q='Engineering the configurational entropy of the material by introducing more elements stabilizes the thermoelectrically beneficial high-symmetry.-phase and promotes the multivalley electronic structure of the valence band.'
r('introducing more elements','d','engineers','configurational entropy','q',q,'thermo','Cu7P(SxSe1-x)6')
r('configurational-entropy engineering by introducing more elements','d','stabilizes','high-symmetry phase','s',q,'thermo','Cu7P(SxSe1-x)6')
r('configurational-entropy engineering by introducing more elements','d','promotes','multivalley valence-band electronic structure','s',q,cond='Cu7P(SxSe1-x)6')
q='Engineering the configurational entropy of the material by introducing more elements stabilizes the thermoelectrically beneficial high-symmetry.-phase and promotes the multivalley electronic structure of the valence band. As a result, a remarkable improvement of the Seebeck coefficient and a reduction of electrical resistivity were observed for the investigated alloys.'
r('configurational-entropy engineering','d','improves','Seebeck coefficient','q',q,cond='investigated Cu7P(SxSe1-x)6 alloys')
r('configurational-entropy engineering','d','reduces','electrical resistivity','q',q,cond='investigated Cu7P(SxSe1-x)6 alloys')
q='The combined effect of the extremely low lattice thermal conductivity and enhanced power factor leads to the significant enhancement of the thermoelectric figure of merit ZT up to similar to 0.75 at 673 K for the Cu7P(SxSe1-x)(6) (x = 0.5) sample with the highest configurational entropy, which is around twice higher compared with the pure selenide and almost four times higher than sulfide.'
r('extremely low lattice thermal conductivity and enhanced power factor','q','enhance','ZT','q',q,cond='x=0.5 highest configurational entropy sample; ~0.75 at 673 K; ~2 times pure selenide, ~4 times sulfide',joint=['extremely low lattice thermal conductivity','enhanced power factor'])
paper('P1199','unspecified','review','review_synthesis: specific synthesis of keff role retained; topic lists and future research directions excluded.')
q='Among the key performance indicators, the effective thermal conductivity (keff) plays a crucial role in maintaining internal temperature gradients and enhancing overall energy conversion efficiency of thermocells.'
r('effective thermal conductivity','q','plays a crucial role in maintaining','internal temperature gradients','q',q,'thermal','ionic thermocells',note='review_synthesis; no direction of conductivity change inferred')
r('effective thermal conductivity','q','plays a crucial role in enhancing','energy conversion efficiency','q',q,'thermal','ionic thermocells',note='review_synthesis; no monotonic direction inferred')
paper('P1803','computational')
q='To address this need through computations, we build upon our previously developed isotropic model for kappa(L) and incorporate the directional (angular) dependence by using the elastic tensor obtained from ab initio calculations and the Christoffel equations for the speed of sound.'
r('ab initio elastic tensor and Christoffel equations','d','incorporate into thermal-conductivity model','directional dependence of speed of sound','q',q,'method',joint=['ab initio elastic tensor','Christoffel equations'])
q='With the anisotropic speed of sound and intrinsic material properties as input parameters, we can predict the direction-dependent kappa(L)(theta,phi).'
r('anisotropic speed of sound and intrinsic material properties','x','enable model prediction of','direction-dependent lattice thermal conductivity','q',q,'method',joint=['anisotropic speed of sound','intrinsic material properties'])
r('new anisotropic thermal-conductivity model','d','predicts within average factor difference 1.8 of','experimental lattice thermal conductivity','q','We validate this new model by comparing with the experimental data from the literature-the predicted kappa(L) is within an average factor difference of 1.8 of experimental measurements, spanning 5 orders of magnitude in kappa(L).','method','literature experimental validation spanning 5 orders of magnitude')
paper('P0707','theoretical')
q='Results are given about the parametric excitation of thermoelectric instability in a liquid semiconductor or an ionic melt layer subject to a harmonically time varying heat flux normal to its top open surface.'
r('harmonically time-varying heat flux','c','parametrically excites','thermoelectric instability','p',q,'thermo','liquid semiconductor or ionic melt layer; flux normal to top surface open to air')
r('integer disturbances','p','are most destabilizing for','liquid quasiequilibrium','s',"First, it is shown that for a purely thermoelectric instability the 'integer' disturbances are the most dangerous ones for the liquid quasiequilibrium.",'thermo','purely thermoelectric instability in liquid semiconductor or ionic melt layer')
paper('P0498','mixed')
q='While a canonical, constant-volume thermodynamic model indicates that greater disparity and longer aliphatic groups should exhibit larger Seebeck coefficients, we instead measure the opposite: Longer aliphatic chains correlate with lower densities and greater heat expansion, stronger intermolecular associations, stronger steric repulsion, and lower Seebeck coefficients.'
for o,t in [('lower density','q'),('greater heat expansion','q'),('stronger intermolecular associations','i'),('stronger steric repulsion','i'),('lower Seebeck coefficient','q')]:
 r('longer aliphatic chains','s','correlate with',o,t,q,'thermo','five anhydrous 1-methyl-3-alkylimidazolium halide ILs; high-aspect-ratio horizontal-temperature-gradient geometry with minimal convection',assertion='association',mod='experimental')
r('greater disparity and longer aliphatic groups','s','are predicted to increase','Seebeck coefficient','q',q,'thermo','canonical constant-volume thermodynamic model; experimentally opposite trend observed',joint=['greater disparity','longer aliphatic groups'],mod='theoretical')
q='As evidence of the critical role of thermal expansion, we measure that the Seebeck effect is nonlinear: Values of -2.8 mV/K with a 10 K temperature difference and -1.8 mV/K with a 50 K difference are measured with ether ion.'
r('temperature difference','c','nonlinearly changes','Seebeck coefficient','q',q,'thermo','source ether ion; -2.8 mV/K at 10 K and -1.8 mV/K at 50 K',mod='experimental',status='uncertain',note='ether ion identity not defined; retained source phrasing')
r('heat expansion','q','negatively correlates with','Seebeck coefficient','q','Our results indicate that steric repulsion and heat expansion are important considerations in ionic liquid design; with large temperature differences, the Seebeck coefficient correlates negatively with heat expansion.','thermo','large temperature differences',assertion='association',mod='experimental')
r('limiting thermal expansion and steric forces','d','may improve','Seebeck values','q','Our results suggest that Seebeck values may improve if thermal expansion and steric forces are limited in a pressurized, isochoric, convection-free design.','thermo','pressurized isochoric convection-free design',joint=['limited thermal expansion','limited steric forces'],assertion='hypothesis')
paper('P0900',note='Questions analyzed without a reported result, including dilution and Ringer ionic-composition effects, not converted to directional findings.')
r('colloidal component of shaped blood elements','m','determines to greater extent than ionic subsystem','thermoelectromotive-force coefficient','q','The experimental results show that the co efficient of thermoelectromotive force of the blood samples under study is determined to a greater extent by the colloidal component of the shaped elements than by the contribution of the ionic subsystem.',cond='studied animal blood samples')
r('thermoelectric phenomena in biological fluids','p','can affect activation of','biochemical processes in animals','p','The results obtained indicate that thermoelectric phenomena in biological fluids can affect the activation of bio chemical processes in the body of animals.','app',assertion='hypothesis')
paper('P1807')
q='Here, a simple way of realizing a 2DHG with an ultrahigh mobility of 24 000 cm(2) V-1 s(-1) is demonstrated using an interface between STO and a thin amorphous FeOy layer, made by depositing a sub-nanometer-thick Fe layer on an STO substrate at room temperature.'
r('STO/thin amorphous FeOy interface','s','realizes','2D hole gas with ultrahigh mobility','s',q,cond='sub-nanometer Fe deposited on STO at room temperature; mobility 24000 cm(2) V-1 s(-1)')
r('sub-nanometer Fe deposition on STO','d','forms','STO/thin amorphous FeOy interface','s',q,cond='room temperature')
r('controlling Fe thickness','d','switches','carrier type from p-type 2DHG to n-type 2DEG','x','The carrier type can be switched from p-type (2DHG) to n-type (2DEG) by controlling the Fe thickness.',cond='STO/FeOy interface')
paper('P0720','unspecified')
q='The presented integrated concept provides both rapid initial response upon heating and stable synergistically enhanced signals upon prolonged exposure to heat stimuli.'
r('thermodiffusion-assisted pyroelectrics','d','provides','rapid initial response','f',q,'app','upon heating; integrated pyroelectric and ionic thermoelectric materials')
r('thermodiffusion-assisted pyroelectrics','d','provides','stable synergistically enhanced signals','f',q,'app','prolonged exposure to heat stimuli')
r('incorporation of plasmonic metasurfaces','d','enables','rapid and stable signals for radiation-induced heating','f','Likewise, incorporation of plasmonic metasurfaces enables the concept to provide both rapid and stable signals for radiation-induced heating.','app','thermodiffusion-assisted pyroelectrics')
r('ion-electron interactions','i','explain','performance and working mechanism of thermodiffusion-assisted pyroelectrics','p','The performance of the concept and its working mechanism can be explained by ion-electron interactions at the interface between the pyroelectric and ionic thermoelectric materials.',cond='interface between pyroelectric and ionic thermoelectric materials')
r('ion-electron interactions','i','occur at','pyroelectric/ionic thermoelectric interface','s','The performance of the concept and its working mechanism can be explained by ion-electron interactions at the interface between the pyroelectric and ionic thermoelectric materials.')
paper('P0895',note='Unspecified proposed formation mechanism and isolated power-factor examination omitted.')
r('microwave-assisted heating in C8H15BrN2 RTIL','d','synthesizes','plate-like Bi2Te3 crystals','s','Bi2Te3 crystals with plate-like morphology have been successfully synthesized via a microwave-assisted heating approach in room temperature ionic liquid (RTIL) of 1-butyl-3-methylimidazolium bromide (C8H15BrN2).')
r('as-synthesized Bi2Te3','m','has','hexagonal plate morphology','s','Scanning electronic microscopy (SEM) observation of as-synthesized Bi2Te3 confirmed their morphology of the hexagonal plates.')
q='High-resolution transmission electronic microscopy (HR-TEM) and selected area electron diffraction (SAED) results revealed that the Bi2Te3 plates are of single-crystal in nature with the growth direction of < 1 1 (2) over bar 0 >.'
r('Bi2Te3 plates','m','are','single crystals','s',q)
r('Bi2Te3 plates','m','grow along','< 1 1 (2) over bar 0 > direction','x',q)
r('increasing ionic liquid amount','c','changes morphology sequentially','nanorod/nanoplate mixture to regular hexagonal plates to nanoplates with small flecks','s','In addition, as increasing the amount of ionic liquid, SEM results showed a novel evolution process of Bi2Te3 morphologies from mixture of Bi2Te3 nanorods and nanoplates to regular hexagonal plates, and then nanoplates with many small flecks.',cond='microwave-assisted Bi2Te3 synthesis with C8H15BrN2')
save('batch02.json')
