# -*- coding: utf-8 -*-
"""Verify frozen mapping evidence, export bridges and a local comparison viewer."""
import base64,collections,csv,gzip,hashlib,json,time
from pathlib import Path
D=Path(__file__).resolve().parent;ROOT=D.parent;H=ROOT.parent
def read(p):return json.loads(p.read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def csvout(path,rows):
 with path.open('w',encoding='utf-8-sig',newline='') as f:
  w=csv.DictWriter(f,fieldnames=sorted({k for r in rows for k in r}));w.writeheader()
  for r in rows:w.writerow({k:json.dumps(v,ensure_ascii=False) if isinstance(v,(list,dict)) else v for k,v in r.items()})
def main():
 for p,h in read(D/'freeze.json')['files'].items():assert sha(Path(p))==h,p
 m=read(D/'judge_manifest.json');usage=collections.Counter();outputs=[]
 for j in m['jobs']:
  r=D/'runs'/j['id'];meta=read(r/'SUCCESS.json');assert sha(r/'response.json')==meta['response_sha256'];assert sha(D/'jobs'/(j['id']+'.json'))==meta['input_sha256']==j['input_sha256'];outputs+=read(r/'response.json')['pairs']
  for p in r.glob('attempt_*/events.jsonl'):
   for line in p.read_text().splitlines():
    try:e=json.loads(line)
    except json.JSONDecodeError:continue
    if e.get('type')=='turn.completed':usage.update(e.get('usage',{}))
 packets={p['review_id']:p for p in read(D/'review_packets.json')};selection={p['review_id']:p for p in read(D/'selection.json')}
 assert len(outputs)==len(packets) and {x['review_id'] for x in outputs}==set(packets)
 graphs={d:read(ROOT/'graph'/d/'graph.json') for d in ['iTE','TG']};edges={e['claim_id']:e for g in graphs.values() for e in g['edges']};evidence_positions=0;allrows=[];bridges=[];papers=set()
 for x in outputs:
  p=packets[x['review_id']];row=dict(x,selection=selection[x['review_id']]);views={};paths={}
  for side in ['left','right']:
   v=p[side];claim=v['claim'];papers.add(claim['paper_id']);assert edges[claim['claim_id']]==claim
   for e in [claim]+v['same_paper_neighbor_claims']:
    assert e==edges[e['claim_id']] and e['paper_id']==claim['paper_id']
    assert len(e['evidence_spans'])==len([e['quote']]+e['context_quotes'])
    for q,span in zip([e['quote']]+e['context_quotes'],e['evidence_spans']):assert v['abstract'][span['start']:span['end']]==q;evidence_positions+=1
   chosen=[claim]+[e for e in v['same_paper_neighbor_claims'] if e['claim_id'] in x['neighbor_claim_ids']]
   paths[side]=[dict(first=a['claim_id'],second=b['claim_id'],nodes=[a['source'],a['target'],b['target']]) for a in chosen for b in chosen if a['claim_id']!=b['claim_id'] and a['target']==b['source']]
   views[side]=dict(claim=claim,abstract=v['abstract'],neighbors=[e for e in v['same_paper_neighbor_claims'] if e['claim_id'] in x['neighbor_claim_ids']],concepts=v['endpoint_concepts'])
  row.update(views=views,explicit_same_paper_paths=paths);allrows.append(row)
  for ep in x['endpoint_maps']:
   a=p['left']['claim'];b=p['right']['claim'];lf='source' if ep['left_endpoint']=='subject' else 'target';rf='source' if ep['right_endpoint']=='subject' else 'target'
   bridges.append(dict(review_id=x['review_id'],left_concept_id=a[lf],right_concept_id=b[rf],kind=ep['kind'],reason=ep['reason'],scope='selected_claim_context_only_not_global_sameAs',left_claim=a['claim_id'],right_claim=b['claim_id'],left_support=x['left_support'],right_support=x['right_support'],relation_match=x['match']))
 allrows.sort(key=lambda x:(-x['match'],x['review_id']));write(D/'mapping_results.json',allrows);write(D/'concept_bridges.json',bridges);csvout(D/'concept_bridges.csv',bridges)
 csvout(D/'relation_mapping.csv',[dict(review_id=x['review_id'],left_claim=x['views']['left']['claim']['claim_id'],right_claim=x['views']['right']['claim']['claim_id'],**{k:x[k] for k in ['match','level','left_support','right_support','left_physics','right_physics','left_working_stage','right_working_stage','conditions','physical_boundary','explanation','local_structure_assessment','limitations']}) for x in allrows])
 stats=dict(retrieval=read(D/'retrieval_summary.json'),reviewed_pairs=len(allrows),relation_match_counts=dict(collections.Counter(x['match'] for x in allrows)),level_counts=dict(collections.Counter(x['level'] for x in allrows)),concept_bridge_counts=dict(collections.Counter(x['kind'] for x in bridges)),physics_pairs=dict(collections.Counter(x['left_physics']+' → '+x['right_physics'] for x in allrows)),clear_cross_physics_pairs=[x['review_id'] for x in allrows if x['match']==2 and x['left_physics']!=x['right_physics'] and 'other_unclear' not in [x['left_physics'],x['right_physics']]],evidence_positions_verified=evidence_positions,usage=dict(usage),semantic_authority='Astra-medium exploratory model review; not human gold, not method comparison, not transfer validation',source_graphs_unchanged=True,completed_at=time.time())
 write(D/'summary.json',stats);write(D/'contacted_papers.json',dict(paper_ids=sorted(papers),purpose='Exploratory mapping review; not untouched future acceptance sample'))
 payload=base64.b64encode(gzip.compress(json.dumps(dict(summary=stats,rows=allrows),ensure_ascii=False,separators=(',',':')).encode())).decode()
 (D/'index.html').write_text(TEMPLATE.replace('__PAYLOAD__',payload))
 counts=stats['relation_match_counts'];lines=['# 新版两图映射：探索性交付','',f"新版 iTE/TG 图谱产生 {stats['retrieval']['concept_candidates']:,} 对概念候选、{stats['retrieval']['relation_candidates']:,} 对核心关系候选。已对 {len(allrows)} 对进行一次完整摘要核查：明确对应 {counts.get(2,0)} 对、有限对应 {counts.get(1,0)} 对、不支持 {counts.get(0,0)} 对。未核查候选保持未核查，不能将上述计数解释为总体准确率。",'', '## 依据与边界','', '建议来自项目目标、先前24对探索诊断和相关方法研究，不是iTE/TG上已证实的最优算法。', '', '- [RDGCN，IJCAI 2019](https://www.ijcai.org/proceedings/2019/733)：使用关系与邻域支持同实体对齐，不能直接证明跨机制迁移。','- [Gentner，1983](https://groups.psych.northwestern.edu/gentner/papers/Gentner83.2b.pdf)：区分关系结构类比与表面相似，是理论依据。','', '本轮没有复现RDGCN，也没有采用GNN训练。词汇TF-IDF用于候选检索，模型根据完整摘要和同篇邻边独立核查。结构信息是否比名称基线更有效，需固定候选与评价标准另做受控实验，本轮未检验。', '', '源图尚未全面达到抽取质量目标，所以核查先判断每条关系的原文支持。关系对应、概念同义、物理机制和工作阶段分别记录；局部路径只从同篇实际有向边构造，不从多篇拼接因果链。图中路径存在本身也不证明机制类比成立。', '', f"概念判定计数（每对关系两个定向端点，可能重复同一概念对）：{json.dumps(stats['concept_bridge_counts'],ensure_ascii=False)}。这些映射仅针对已核查主张语境，不全局合并概念或传递sameAs。", '', f"明确关系对应中，实际机制类别不同且均非unknown的对：{json.dumps(stats['clear_cross_physics_pairs'])}。该列表仍不等于科学迁移可行。", '', '## 文件','', '- [交互映射页](index.html)：可按明确/有限/不支持、物理类型和关键词筛选，查看双方关系与原文。','- [逐对结果](mapping_results.json)、[关系CSV](relation_mapping.csv)','- [概念对应JSON](concept_bridges.json)、[概念对应CSV](concept_bridges.csv)','- [全部概念候选](concept_candidates.csv)、[全部关系候选](relation_candidates.csv)','- [未检出概念候选](concepts_without_candidate.json)、[未检出关系候选](relations_without_candidate.json)','- [协议](PROTOCOL.md)、[选样](selection.json)、[原始模型输出](judgments.json)','', f"程序核对了 {evidence_positions:,} 处原文证据位置，输入图谱哈希不变。程序核验不等于语义真值。记录输入 {usage['input_tokens']:,} / 输出 {usage['output_tokens']:,} tokens；不含此前全库修订成本。", '', '本页主要展示有逐对核查的探索结果。词汇检索容易遗漏措辞差异大的类比，未建立总体候选召回率；部分节点仍未完成充分别名归一化。没有得到全库已验证对齐，也没有完成正式四组对照或全文/SI验证。']
 (D/'REPORT.md').write_text('\n'.join(lines)+'\n');print(json.dumps(stats,ensure_ascii=False),flush=True)

TEMPLATE=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>iTE ↔ TG · 跨图映射</title>
<style>:root{font-family:system-ui,-apple-system,sans-serif;color:#243841;background:#f3f6f7}*{box-sizing:border-box}body{margin:0}header{background:#113b43;color:white;padding:26px 4vw}h1{font-size:26px;margin:0 0 8px}header p{margin:0;color:#cde1e4}main{padding:24px 4vw;max-width:1500px;margin:auto}.notice{background:#fff6e7;border-left:4px solid #bd9147;padding:12px 16px;font-size:13px;line-height:1.7}.stats,.filters,.links{display:flex;gap:12px;flex-wrap:wrap;margin:18px 0}.stat{background:white;padding:15px 22px;border:1px solid #dfe7e8;border-radius:8px;flex:1}.stat b{display:block;font-size:27px;color:#126675}.stat span{font-size:13px}input,select,button{font:inherit;border:1px solid #c4d2d6;border-radius:6px;padding:9px;background:white}input{flex:1;min-width:240px}.layout{display:grid;grid-template-columns:310px 1fr;gap:20px}.panel{background:white;border:1px solid #dee6e8;border-radius:10px;padding:20px}#list{max-height:750px;overflow:auto}#list button{display:block;width:100%;text-align:left;margin-bottom:8px;font-size:13px;line-height:1.5;cursor:pointer}#list button.active{border-color:#087587;background:#eff8f8}.badge{display:inline-block;padding:3px 8px;border-radius:4px;font-size:12px;background:#e8eff2;margin:2px}.v2{background:#dcf2e8;color:#166049}.v1{background:#fff0d3;color:#78510e}.v0{background:#fce5e5;color:#8e3232}h2{font-size:20px;margin-top:0}h3{font-size:15px;margin-bottom:8px}p{line-height:1.65;font-size:14px}.twins{display:grid;grid-template-columns:1fr 1fr;gap:16px}.claim{border:1px solid #cfdee1;border-radius:8px;padding:15px;overflow-wrap:anywhere}.claim.ite{border-top:4px solid #137286}.claim.tg{border-top:4px solid #937534}.claim .pred{color:#186b79;font-weight:bold;margin:10px 0}.small{font-size:12px;color:#617780}.concept{font-size:14px;line-height:1.6}.evidence{margin-top:15px}summary{cursor:pointer;font-size:14px;padding:8px 0}blockquote{margin:8px 0;padding:12px 16px;background:#f3f6f7;border-left:3px solid #82a9b1;line-height:1.6;font-size:13px;white-space:pre-wrap}table{width:100%;border-collapse:collapse;font-size:13px}td,th{text-align:left;border-bottom:1px solid #e0e8e9;padding:10px;vertical-align:top}a{color:#126878}.links{font-size:13px}.empty{padding:24px;color:#657b80}@media(max-width:900px){.layout,.twins{grid-template-columns:1fr}#list{max-height:220px}}</style>
<header><h1>iTE ↔ TG · 跨图映射</h1><p>概念对应 · 定向关系 · 同篇局部结构 · 双方原文</p></header><main><div class="notice">探索结果：对应关系不等于材料可迁移。候选检索分数不是语义概率；未核查候选不算确认或否定。源图尚未全面达到质量目标，每对结果另列原文支持情况。</div><div id="loading">正在读取映射…</div><div id="app" hidden><div class="stats" id="stats"></div><div class="filters"><input id="search" aria-label="搜索映射" placeholder="搜索节点、关系、论文编号或解释…"><select id="verdict" aria-label="对应等级"><option value="all">全部对应等级</option><option value="2">明确对应</option><option value="1">有限对应</option><option value="0">不支持对应</option></select><select id="physics" aria-label="机制筛选"><option value="all">全部物理类别</option><option value="cross">双方类别不同且明确</option><option value="same">相同物理类别</option><option value="unknown">含未明确物理类别</option></select></div><div class="layout"><aside class="panel"><h2>已核查映射</h2><p id="count" class="small"></p><div id="list"></div></aside><section class="panel" id="detail"></section></div><div class="links"><a href="../graph/index.html">打开域内图谱</a><a href="relation_mapping.csv" download>核查结果CSV</a><a href="concept_bridges.csv" download>概念对应CSV</a><a href="concept_candidates.csv" download>全部概念候选（未逐对核查）</a><a href="relation_candidates.csv" download>全部关系候选（未逐对核查）</a><a href="REPORT.md">方法依据与报告</a></div></div></main>
<script id="payload" type="application/octet-stream">__PAYLOAD__</script><script>
let DATA,selected;const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const verdict=['不支持对应','有限对应','明确对应'],physics={ionic_thermodiffusion:'离子热扩散',thermogalvanic_redox:'热电化学/氧化还原',electronic_thermoelectric:'电子热电',hybrid:'混合机制',other_unclear:'其他/未明确'},kinds={equivalent_in_context:'当前主张语境同义',analogous_role:'功能/角色类比',related_not_equivalent:'相关但不等价',different:'不同',uncertain:'待定'},support={supported:'完整支持',partial:'部分支持',unsupported:'不支持',uncertain:'待定'};
function badge(x){return '<span class="badge v'+x.match+'">'+verdict[x.match]+'</span>'}
function search(){const q=$('search').value.trim().toLowerCase(),v=$('verdict').value,ph=$('physics').value;const rows=DATA.rows.filter(x=>{const unknown=[x.left_physics,x.right_physics].includes('other_unclear');return(v==='all'||x.match===Number(v))&&(ph==='all'||ph==='cross'&&!unknown&&x.left_physics!==x.right_physics||ph==='same'&&!unknown&&x.left_physics===x.right_physics||ph==='unknown'&&unknown)&&(!q||JSON.stringify([x.review_id,x.explanation,x.views.left.claim.subject,x.views.left.claim.object,x.views.right.claim.subject,x.views.right.claim.object,x.views.left.claim.paper_id,x.views.right.claim.paper_id]).toLowerCase().includes(q))});$('count').textContent=rows.length+' / '+DATA.rows.length+' 对';$('list').innerHTML=rows.map(x=>'<button data-id="'+x.review_id+'" class="'+(x.review_id===selected?'active':'')+'">'+badge(x)+' '+esc(x.review_id)+'<br>'+esc(x.views.left.claim.subject)+' → '+esc(x.views.left.claim.object)+'<br><span class="small">↔ '+esc(x.views.right.claim.subject)+' → '+esc(x.views.right.claim.object)+'</span></button>').join('');$('list').querySelectorAll('button').forEach(b=>b.onclick=()=>select(b.dataset.id));if(rows.length&&!rows.some(x=>x.review_id===selected))select(rows[0].review_id);if(!rows.length)$('detail').innerHTML='<p class="empty">没有符合筛选的已核查映射。</p>'}
function graphLink(e,side){return '../graph/index.html?domain='+e.domain+'&node='+encodeURIComponent(e[side==='subject'?'source':'target'])}
function claim(x,side){const v=x.views[side],e=v.claim;return '<div class="claim '+(side==='left'?'ite':'tg')+'"><h3>'+e.domain+' · '+esc(e.paper_id)+'</h3><div class="concept"><a target="_blank" href="'+graphLink(e,'subject')+'">'+esc(e.subject)+'</a><div class="pred">↓ '+esc(e.predicate)+'</div><a target="_blank" href="'+graphLink(e,'object')+'">'+esc(e.object)+'</a></div><p>原文：'+support[x[side+'_support']]+'<br>机制：'+physics[x[side+'_physics']]+'<br>阶段：'+esc(x[side+'_working_stage'])+'</p><p class="small">条件：'+esc(e.conditions||'未报告')+'<br>共同因素：'+esc(e.joint_factors.join('；')||'未报告')+'<br>断言：'+esc(e.assertion)+'</p><details class="evidence"><summary>查看关系证据与文献</summary><p>'+esc(e.paper_title)+'</p>'+[e.quote,...e.context_quotes].map(q=>'<blockquote>'+esc(q)+'</blockquote>').join('')+'<small>'+esc(e.claim_id)+'</small></details><details><summary>完整摘要</summary><blockquote>'+esc(v.abstract)+'</blockquote></details></div>'}
function select(id){selected=id;const x=DATA.rows.find(x=>x.review_id===id);$('detail').innerHTML='<h2>'+esc(id)+' · '+verdict[x.match]+'</h2>'+badge(x)+'<p>'+esc(x.explanation)+'</p><div class="twins">'+claim(x,'left')+claim(x,'right')+'</div><h3>概念对应（仅限上述主张语境）</h3><table><tr><th>端点</th><th>判定</th><th>依据</th></tr>'+x.endpoint_maps.map(y=>'<tr><td>'+(y.left_endpoint==='subject'?'主体 ↔ 主体':'客体 ↔ 客体')+'</td><td>'+kinds[y.kind]+'</td><td>'+esc(y.reason)+'</td></tr>').join('')+'</table><h3>局部结构与边界</h3><p>'+esc(x.local_structure_assessment)+'</p><p>'+esc(x.physical_boundary)+'</p><p class="small">'+esc(x.limitations)+'</p>'+['left','right'].map(side=>'<details><summary>'+ (side==='left'?'iTE':'TG')+' 实际采用的邻边（'+x.views[side].neighbors.length+'）</summary>'+x.views[side].neighbors.map(e=>'<p>'+esc(e.subject)+' → '+esc(e.predicate)+' → '+esc(e.object)+'<br><small>'+esc(e.claim_id)+'</small></p>').join('')+'<small>已提供边中可直接连接的同篇有向二步路径：'+x.explicit_same_paper_paths[side].length+'。存在路径不自动证明类比成立。</small></details>').join('')+(x.insight_question?'<h3>可供后续核查的问题</h3><p>'+esc(x.insight_question)+'</p>':'');$('list').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.id===id))}
async function start(){try{const bytes=Uint8Array.from(atob($('payload').textContent.trim()),c=>c.charCodeAt(0));DATA=JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text());$('loading').hidden=true;$('app').hidden=false;const s=DATA.summary;$('stats').innerHTML=[[s.reviewed_pairs,'逐对原文核查'],[s.relation_match_counts['2']||0,'明确关系对应'],[s.relation_match_counts['1']||0,'有限对应'],[s.relation_match_counts['0']||0,'不支持对应']].map(([n,l])=>'<div class="stat"><b>'+n+'</b><span>'+l+'</span></div>').join('');$('search').oninput=search;$('verdict').onchange=search;$('physics').onchange=search;search()}catch(e){$('loading').textContent='加载失败：'+e.message}}start();
</script></html>'''
if __name__=='__main__':main()
