import json
from pathlib import Path
O=Path(__file__).parent
rows=[]
def p(pid,cs,rs,note=''):
 rows.append(dict(paper_id=pid,candidates=[dict(candidate_id='CTG-'+i,label=l,error_tags=t.split(','),reason=r) for i,l,t,r in cs],references=[dict(reference_id='G'+pid+'-'+i,label=l,reason=r,**({'full_coverage_sets':[['CTG-'+v for v in s.split('+')] for s in full.split(',') if s], 'partial_candidates':['CTG-'+v for v in part.split(',') if v]} if l=='valid' else {})) for i,l,r,full,part in rs],note=note))
p('P0330',[('0011','supported','none','年复补入含氧水在该环空环境形成电化学电池明确。'),('0051','supported','none','低阻电解液导致强腐蚀环境明确。'),('0052','supported','none','含氧水与水泥浸出盐共同形成低阻电解液明确。'),('0086','supported','none','保留高套管温度及增大温差的整体归因，未强拆分词从句。'),('0097','supported','none','反复地表水进入水泥顶以上引起套管腐蚀明确。'),('0108','supported','none','约125℉套管温度加快腐蚀明确。'),('0132','supported','none','套管升温增加与导管温差明确。'),('0140','supported','none','所形成电化学电池腐蚀套管明确。')],[('001','valid','补含氧水形成电池明确。','0011',''),('002','valid','套管升温增大温差明确。','0132',''),('003','valid','套管升温加快腐蚀明确。','0108',''),('004','uncertain','creating从句可归于高温及温差变化整体，单独将梯度设为无条件成因超出可确定归属。','',''),('005','valid','水与盐共同产生低阻电解液明确。','0052',''),('006','valid','低阻电解液导致腐蚀环境明确。','0051',''),('007','valid','反复进水引起腐蚀明确。','0097',''),('008','valid','电池腐蚀套管明确。','0140','')],'原文OCR有casino/catsing等拼写损坏，上下文明确为casing；未据常识新增机制。')
p('P0221',[('0007','supported','none','可分离交直流电压共同支持同步力温传感明确。'),('0059','supported','none','保留形变可诱导脉冲电压能力。'),('0077','supported','none','保留跨液滴温差可诱导直流电压能力。'),('0117','supported','none','逆电润湿和热电效应共同构成自供能多模态传感明确。')],[('001','valid','induces可理解为作者报告的诱导能力。','0059',''),('002','valid','两信号同步感知两量明确。','0007',''),('003','valid','双效应支撑传感器明确。','0117',''),('004','valid','温差诱导直流电压能力明确。','0077','')])
p('P0118',[('0060','supported','none','NaOH中仅30℃以下碳钢相对不锈钢为阴极明确。'),('0103','supported','none','含氯Ca(OH)2中碳钢持续为阳极明确。'),('0120','supported','none','混凝土梁热侧过30℃由阳转阴明确。'),('0143','supported','none','温度梯度诱导梁段间电流明确。'),('0174','supported','none','指定含氯溶液中电流显著依赖温度明确。')],[('001','valid','指定条件温度依赖明确。','0174',''),('002','valid','含氯溶液阳极行为明确。','0103',''),('003','valid','NaOH及30℃阈值明确。','0060',''),('004','valid','梯度驱动和30℃临界点均明确；同梁的两条可联合覆盖。','0143+0120','0143'),('005','valid','越过30℃极性反转明确。','0120','')])
p('P0153',[('0133','supported','none','保留pH效应似与热效应相当的比较语气。'),('0156','supported','none','原文may预测能力及实验理论相关支持均保留。')],[('001','valid','association保留效应相当的比较性质。','0133',''),('002','uncertain','原文may quantitatively predict仍带可能性，参考改为确定can且author_claim略强，不能强迫候选仿写。','','')])
p('P0103',[('0057','supported','none','电极数对测量电流和功率影响大明确；实验配置角色不改变关系。'),('0091','supported','none','功率除温差平方的归一化不准确为明确负结果。'),('0095','supported','none','三电极组件高估电流功率明确。'),('0106','supported','none','原文全称确定为线性扫描伏安，保留异常缩写。'),('0113','supported','none','测量时间强烈影响电流和功率明确。')],[('001','valid','线性扫描伏安高估明确。','0106',''),('002','valid','归一化准确性负结果明确。','0091',''),('003','valid','测量时间影响明确。','0113',''),('004','valid','电极数量影响明确。','0057',''),('005','valid','三电极高估明确。','0095','')])
(O/'tail1.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2))
